### ISSUE TITLE
Forms page

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#106]
@LHinson If on the forms page we are only going to show error message, maybe we should call it "form validation" something like https://www.google.com/design/spec/patterns/errors.html

If not then we should add the different inputs and ways to use a form, or link to http://getbootstrap.com/css/#forms since its the same on paternfly.

**Comment by LHinson** [comment]
@andresgalante soon we will be including the additional information that Liz has recently worked on. The strategy for the IA was to have a forms page with all the information so this pattern page just would grow over time. None the less, we will be able to address this issue sooner than later since we now have some more overarching content.

**Comment by andresgalante** [comment]
@LHinson cool, so from a code point of view we can add the link to bootstrap forms. 

If anyone wants to implement a form they'll have liz doc telling how they should behave and bootstrap docs telling how the code should look like. What do you think?

**Comment by LHinson** [comment]
Yeah, I think that makes sense @andresgalante. Check out the content that will be posted here: https://docs.google.com/document/d/1UPx4smbKUsbyzL84LoEGlCyI5u89nPNs4cd2I0x4-WM/edit#

Feel free to add in the links appropriately and I'll make sure it gets posted.

**Comment by LHinson** [comment]
@mcarrano has recently revamped all of forms. closing this as it should be addressed with those changes.
