### ISSUE TITLE
Reference Implementation snippets are close on widgets

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#109]
On all widgets the code snippets are collapsed.

**Comment by dlabrecq** [comment]
In the code tabs, it was decided to have the code snippets open. (We never did anything with the widgets because that page is being redesigned.) IMO, the code snippets should all be closed. It makes scrolling a pain because the code can be very large. If I want to see the code, I can click open.

@LHinson Do we want to open all the code snippets on the widgets page?

**Comment by dlabrecq** [comment]
"No change at this time"
