### ISSUE TITLE
Add max-width to markdown content

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-org#1133]
Add a max-width to prevent content from pages authored in markdown from stretching across the entire width of a page. 

Pages impacted:
All content in getting started section
Design guidelines > Usage and behavior
Design guidelines > Content
All descriptions at the top of the component docs pages

**Comment by rachael-phillips** [comment]
@stacymcauliffe can we set up another follow up meeting about this one?

**Comment by rachael-phillips** [comment]
Hi @gdoyle1 one thing that will be good to figure out with this effort is how adding a max-width will effect all of our visuals that have been customized for the current width of the content. To me, that is the biggest design challenge here. Does that make sense? For example, on the typography page: https://www.patternfly.org/v4/design-guidelines/styles/typography. How will things look post adding a max-width to the content?

**Comment by gdoyle1** [comment]
I've been thinking about this for a bit and came up with a solution here!
[Google doc](https://docs.google.com/document/d/1bqzbKJXJxKRY5YEiIC9xcA1V-uvz62wR_qUrOlyi-fo/edit?usp=sharing) explaining thought process
[Marvel project](https://marvelapp.com/5f4c9f6) showing how the typography page would be changing
Colors page will need to be updated per this issue I have as well #722

**Comment by rachael-phillips** [comment]
Hi @gdoyle1 this looks great so far, and the thought process and the Marvel app totally make sense to me! A few questions for you on this one:

1. How do you anticipate this effects the content on our design guidelines pages and our component pages? Would all of our images stay as is?
2. What would our Styles and design guidelines pages look like on mobile?

cc @mcarrano

**Comment by gdoyle1** [comment]
@rachael-phillips 
1a. Styles/design guidelines pages: What I'm thinking is that this max width only applies to text and inline images. So our images would be able to stay but their new max would be 990px rather than the size they are now. And then the text (this includes normal text AND tables/lists) would only extend to 680px.
- Colors page: Design will be changing per the issue #1517 
- Colors for charts: Max width would apply to all text and images - the color swatches + info would be able to stay sized as is since it acts as an image and can be max 990 width
- Icons: Max width would apply to all text and the search field - the icon blocks can remain the size they are now (carbon does it here and it looks like it works https://www.carbondesignsystem.com/guidelines/icons/library)
- Spacers page: Max width would apply to all text and the boxes within the line heights - this may wrap text two 2 lines but shouldn't be a big deal
- Typography page: [Marvel project](https://marvelapp.com/5f4c9f6) Max width would apply to all text and the boxes within the line heights - this may wrap text two 2 lines but shouldn't be a big deal. As seen in Marvel, the type sizes would move to the left.
1b. Component pages: My thought is we can apply the max text width to the tables with the props and the max image width to the embedded components - I don't think this will affect the current experience with them.

2. Styles/design guidelines pages on mobile: Once we get to the breakpoint where the nav disappears, the content can expand to take the whole width as it does now. So, nothing would change on mobile. The max width would only apply on screens larger than that breakpoint.

Does that sound good to you? @rachael-phillips I'm willing to meet with you about this too if that's easier!

**Comment by rachael-phillips** [comment]
Yes, all of this makes sense to me - thank you for the thorough explanation!

**Comment by evwilkin** [comment]
Colors for charts - notes mention color swatches should stay as they are, but they are currently wider than the 990px max-width that images use.  Should we set their container to match the 990px image max width?
Currently:
![colorForCharts_as-is](https://user-images.githubusercontent.com/8651509/72170111-4c873480-339e-11ea-9393-714e339468a9.png)
After resize:
![colorForCharts_sized-down](https://user-images.githubusercontent.com/8651509/72170113-4c873480-339e-11ea-953a-7fb430febddd.png)

**Comment by evwilkin** [comment]
Component page tables - sizing down to 680px (max width for text) causes many fields to wrap, confirming this is the desired behavior:
![component-tables](https://user-images.githubusercontent.com/8651509/72170253-88ba9500-339e-11ea-97ca-6f4b666da7d8.png)

**Comment by evwilkin** [comment]
Spacers & Typography pages - how should the "Correct / Incorrect" section be handled?  It contains both text and images within a container, and currently stretches full width:
Spacing:
![correct-incorrect-sizing](https://user-images.githubusercontent.com/8651509/72170394-d0d9b780-339e-11ea-8c41-ebd8adbdd164.png)
Typography:
![typography-correct-incorrect](https://user-images.githubusercontent.com/8651509/72170395-d0d9b780-339e-11ea-8422-7272699c27bd.png)

**Comment by evwilkin** [comment]
Typography - After moving "Design is where science and art break even." text to the left, I've set the remaining table below to the max-width of 680px as it was previously just sized to 50% width - noting to confirm this is the desired action after moving headline text.
![typography-table-maxwidth](https://user-images.githubusercontent.com/8651509/72170579-1eeebb00-339f-11ea-89bd-a9b275d16138.png)

**Comment by evwilkin** [comment]
Release notes/Training - any changes needed to these designs that stretch full width?
![releasenotes](https://user-images.githubusercontent.com/8651509/72170718-5bbab200-339f-11ea-9abc-4742e8981df4.png)
![Training](https://user-images.githubusercontent.com/8651509/72170719-5bbab200-339f-11ea-8026-c61952b2c82c.png)

**Comment by evwilkin** [comment]
@gdoyle1 added my questions above, thanks for taking a look!

**Comment by gdoyle1** [comment]
> Colors for charts - notes mention color swatches should stay as they are, but they are currently wider than the 990px max-width that images use. Should we set their container to match the 990px image max width?
Yes - set their container to match the 990px image max width!

> Component page tables - sizing down to 680px (max width for text) causes many fields to wrap, confirming this is the desired behavior:
Yes - we'll still size it down to 680px!

> Spacers & Typography pages - how should the "Correct / Incorrect" section be handled? It contains both text and images within a container, and currently stretches full width:
Can you place the "Correct and Incorrect" sections on top of one another?

> Typography - After moving "Design is where science and art break even." text to the left, I've set the remaining table below to the max-width of 680px as it was previously just sized to 50% width - noting to confirm this is the desired action after moving headline text.
Yup, that's great!

> Release notes/Training - any changes needed to these designs that stretch full width?
No changes needed on either of these pages! It's fine for the cards to take the full width of the page since they are a gallery layout and don't include much text like the other pages do.

@evwilkin thank you for clearly stating these questions! Let me know if you have any other ones. And thanks for working on this!

**Comment by evwilkin** [comment]
@gdoyle1 thanks for the replies!  It looks like I missed one last question - should these alerts be sized down to 680px to match the max-width for text?  Thanks!
![Screen Shot 2020-01-13 at 5 02 55 PM](https://user-images.githubusercontent.com/8651509/72295978-9d10c300-3626-11ea-8bd9-51d18b18c67e.png)
![Screen Shot 2020-01-13 at 5 02 48 PM](https://user-images.githubusercontent.com/8651509/72295979-9d10c300-3626-11ea-9f4e-154fab483e67.png)

**Comment by gdoyle1** [comment]
> @gdoyle1 thanks for the replies! It looks like I missed one last question - should these alerts be sized down to 680px to match the max-width for text? Thanks!

I actually think we should make them match the image size so they'd be somewhere in the middle - so 990px if possible!
