### ISSUE TITLE
Suggestion: change nav item "Documentation" -> "Dev documentation"

### ISSUE THREAD

**Issue by bdellasc** [patternfly/patternfly-org#1179]
I noticed in the top nav on the site we say "Design guidelines". Maybe it makes sense to change  "Documentation" -> "Dev documentation". It would align the two nav items grammatically and also help clearly differentiate where designers and devs should look.

**Comment by rachael-phillips** [comment]
Thanks so much for the issue @bdellasc . We did consider this naming but got feedback from developers that the naming didn't make that much sense to them in early user testing with Sara.

**Comment by bdellasc** [comment]
I see - I didn't realize @schizari tested that terminology in the nav. Thanks.

**Comment by schizari** [comment]
Just catching up on this. Thanks @bdellasc for raising this issue. The IA we had for the wireframe testing back in August 2018 is different than the IA we have today. In the wireframe test, ‘Dev Docs’ was under "Documentation" and the actual problem with the terminology was due to the unexpected contents participants saw under that category.
In the wireframe, we only had "Documentation", "Get started", "Contribute" and "Blog" in the top navigation. The participants didn’t seem to have any difficulties navigating to ‘documentation’ because that was the only category that would make sense for any ‘documentation’ related tasks. But now that "Design Guidelines" has made it to the top navigation, I reckon users would have difficulties in differentiating between “Documentation” and “Design Guidelines” because the distinction is not that clear.
I’d suggest doing another IA testing for the new PF IA @rachael-phillips as the results of the test we did a year ago do not seem to be applicable in this new IA.

**Comment by rachael-phillips** [comment]
That description makes sense to me @schizari I'm hoping we can find a time in the near future to test the site.

**Comment by evwilkin** [comment]
@rachael-phillips is there still any follow-up needed here or should we close this out?  As the website redesign is currently in progress this would be a good chance to pull in any changes.

**Comment by rachael-phillips** [comment]
I'll close this out. Thanks for following up!
