### ISSUE TITLE
Incorrect CSS variable value - Form label

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#1186]
https://www.patternfly.org/v4/documentation/react/components/form/#css-variables

Lists the variable
--pf-c-form__label--Color

as #72767b but when using the inspector it is #151515 (which also matches the sketch template).

**Comment by ajacobs21e** [comment]
@mcarrano @LHinson @rachael-phillips  This is fairly urgent on my end because I need to point a developer to this page to use the correct variable values. Is it possible to update this in the next day or two please? Thank you!

**Comment by rachael-phillips** [comment]
Hi @ajacobs21e thanks so much for bringing this to our attention. We are testing the website right now, and won't be making any changes to the live website for the next couple of days. That being said, let's get you the information you need, and we can work on this issue in the meantime. @gdoyle1 do you know what the correct hex is?

**Comment by gdoyle1** [comment]
@ajacobs21e If you are using forms over a white background, then still use our secondary text color (#72767b). If the background is grey instead, contact @mceledonia since there is ongoing work to revise the secondary text color (see this issue for more details if necessary https://github.com/patternfly/patternfly-next/issues/1864)

**Comment by ajacobs21e** [comment]
Thanks @gdoyle1 . Then this story should be to update the examples shown and to update the Sketch library if #72767b is the correct color to use.

**Comment by evwilkin** [comment]
Closing per https://github.com/patternfly/patternfly-org/issues/1193
