### ISSUE TITLE
Experimental features design for the website

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1247]
A requirement to test and validate components prior to release has come a necessity to ensure quality as well as release stability. 

In this issue, design will need to determine how experimental features are shown on the site. Once this design has been approved by stakeholders [1]. A following up issue needs to be created to implement this capability on the site.

**Comment by rachael-phillips** [comment]
@LHinson would love to talk more about this in our 1:1. @jschuler fyi. We have decided to add experimental features on the left-hand navigation and have open issues to support this.

**Comment by rachael-phillips** [comment]
Here is the proposed design:

![image](https://user-images.githubusercontent.com/40275806/60038339-0bd60100-9682-11e9-99b7-1101b86e8d78.png)

**Comment by mcarrano** [comment]
@rachael-phillips I think this design is fine. My only slight concern is whether users will know to look for something in the Experimental category vs just in Components. It also means that once the feature becomes "official" it will move. 

Did you consider just adding the new feature to Components and just tagging it as Experimental? That way we can just remove the label once it no longer has Experimental status.

**Comment by redallen** [comment]
@rachael-phillips Certain properties or examples could also be marked as experimental, not just an entire component.

**Comment by rachael-phillips** [comment]
I see, thank you for your responses! In that case @dana would you be in agreement that we should just tag something that is experimental rather than it being a category?

**Comment by rachael-phillips** [comment]
Seeing that just examples or props could be marked as experimental, I think we should embrace a label to mark anything experimental. I am opting for an E label, a pattern that I have seen in other design systems, because if we do need to add a label to the table that holds our props, we are going to need something smaller. Here is what this will look like. A tooltip appears on hover cc @mcarrano @redallen @dgutride @LHinson @stacymcauliffe 

<img width="852" alt="Screen Shot 2019-06-25 at 10 30 12 AM" src="https://user-images.githubusercontent.com/40275806/60107055-3b454600-9734-11e9-8ba8-6e1ab094bfbd.png">


<img width="752" alt="Screen Shot 2019-06-25 at 10 23 57 AM" src="https://user-images.githubusercontent.com/40275806/60106995-1bae1d80-9734-11e9-9a25-4b7be4bfe251.png">

**Comment by dgutride** [comment]
@rachael-phillips @mcarrano  - adding the label to properties is probably fine. Keep in mind we might not be able to do that for HTML css values - more research will be necessary.  We do think we can differentiate react properties in this way.  

Mixing experimental components with hardened/released ones is going to be problematic for our support experience and could send a confusing message to our users.  Users will need to opt in specifically to get anything marked experimental - putting them along with other components and not differentiating could give the impression that they can install and use them the same way.  I'd rather we keep them separate and test that way instead of mixing them together for our first pass.   These will then also logically move to our hardened component list once they are available - we can even leave a note in the experimental category with information about them being promoted and how to use them now or point toward updated documentation.  It's still not known whether or not we can just delete an experimental component once it is promoted or if we need to keep both around for a time - so keeping them separate will also help with this potential wrinkle.

I'd also question whether or not we want these to be easily discoverable versus found by somebody who is looking for them directly.  We plan on making life a little difficult for adopters so keeping them in a separate location would help us be consistent.

**Comment by stacymcauliffe** [comment]
The copy I provided for OSIO for experimental features: "This experimental feature is in the early stages of testing and may not work as expected."

Carbon has something similar: "Experimental components, designs, and other resources are presented for testing and feedback. They are not intended for production use."

We could say something like 

"This is an experimental feature in the early stages of testing. It is not intended for production use. 

Interested in this feature? Help us get it production-ready with feedback and contributions."

let me know what you guys think. I can try to trim and revise if that's way too long.

**Comment by mcarrano** [comment]
@dgutride thanks for the elaboration on how we intend to deploy experimental features. Given that users need to specifically "opt-in" to adopt these, I agree that it makes sense to split them out. Given what you are saying does it really make sense to have experimental features (e.g. props or examples) inside of a hardened component or would this make sense to be offered as an experimental version of that component in the Experimental features area?

**Comment by rachael-phillips** [comment]
Great question @mcarrano. I have the same question @dgutride

**Comment by dgutride** [comment]
@mcarrano  - we aren't able to do offer both an experimental version of a component and the released version technically right now for the first pass.  We could possibly offer experimental add-ons but that would be another few weeks of investigative work to do.  

Ideally - we'd focus on delivering new experimental components as the simpler use case first and then expand in a secondary phase to add experimental enhancements to components.  My concern with allowing the latter is that it's a very slippery slope to do this once a component is released, we need to talk a lot more about what you'd introduce as an experimental enhancement to something that we've already released and then work through the user experience of adopting these.

**Comment by rachael-phillips** [comment]
There needs to be a label - "this is outdated now" - please use the official component and link to it.

**Comment by rachael-phillips** [comment]
Here's the design updated per our conversation on Friday. This is the state to warn users if an experimental feature will **not** be brought into the core set of components. @mcarrano do you feel like we are ready to move forward with this design?

<img width="956" alt="Screen Shot 2019-07-01 at 9 05 54 AM" src="https://user-images.githubusercontent.com/40275806/60438823-91583480-9bdf-11e9-9a1a-56150020fadd.png">

**Comment by mcarrano** [comment]
I think this is OK @rachael-phillips . The only thing I will say is that in looking at this again, it feels like having the inline alert and the badge with tooltip is redundant. Do we really need both?

Also, the inline alert should not have a drop shadow. This seems to be a bug in the Sketch library so I will file it there.

**Comment by rachael-phillips** [comment]
@mcarrano this would only be for the use case in which we have decided not to continue forward in pursuing this component. Otherwise it would just be the badge that is shown. In that case, do you think this design makes sense? Curious to hear what you think!

**Comment by mcarrano** [comment]
Thanks for clarifying @rachael-phillips In that case it does make more sense. I'm wondering if the wording on the two messages can be clarified in that case. 

For the tooltip, I would suggest, "This is an experimental feature that is made available for testing and early adoption, only. Be aware that it is subject to change."  Saying that it "may not work as expected" sounds kind of scary, I think.

I am also not sure exactly what you are trying to say with the inline message. Is it that the component is being dropped? Is it that there is a different production ready component that folks should use instead?

**Comment by rachael-phillips** [comment]
@mcarrano yes, that's right - it is basically being deprecated but we still need to keep the documentation available. With this message, I don't think there will be a counterpart that is complete. That being, said I could create another message that says - "A production ready component is available" and link to that component. 

So there would be three states
1. Experimental feature, no warning.
2. Experimental feature with an inline alert warning that this component is not going to be picked up for further development.
3. Experimental feature with inline alert warning / info  that another updated component is available to be used with a link to that component provided. 

@stacymcauliffe what are your thoughts on copy for these states? @mcarrano got us started above.

**Comment by stacymcauliffe** [comment]
Hi guys --

For the tooltip, I think the suggestion I made earlier in this thread would still work: **This is an experimental feature in the early stages of testing. It's not intended for production use.**

For the inline alerts:
State 2. **This experimental feature has been deprecated and will be removed in a future release. We recommend you avoid or move away from using this feature in your projects.** 

State 3. **This experimental feature has been deprecated and will be removed in a future release. Use the [production-ready version of this feature](url) instead.**

Let me know what you think!

**Comment by rachael-phillips** [comment]
That sounds good to me! @mcarrano do you think we're ready to move forward?

**Comment by mcarrano** [comment]
Sure. Looks good to me. Thanks @rachael-phillips @stacymcauliffe

**Comment by christiemolloy** [comment]
@rachael-phillips @mcarrano could you let me know when this is ready to implement on the site / attach a sketch file that I can reference?

**Comment by rachael-phillips** [comment]
Reopening this issue because we still need to implement the design

**Comment by rachael-phillips** [comment]
We'll offer 2/3 states in Core - we will not offer state 3 in React and all 3 in React.

**Comment by rachael-phillips** [comment]
<img width="878" alt="Screen Shot 2019-08-06 at 4 45 00 PM" src="https://user-images.githubusercontent.com/40275806/62575821-97d66d80-b869-11e9-98d3-98b0840fe0a7.png">

**Comment by mcarrano** [comment]
@rachael-phillips can we use the new inline alert styling that does not have the drop shadow?

**Comment by rachael-phillips** [comment]
Great idea, @mcarrano !

**Comment by rachael-phillips** [comment]
Design updated: <img width="1214" alt="Screen Shot 2019-08-08 at 2 55 49 PM" src="https://user-images.githubusercontent.com/40275806/62730022-29221d00-b9ed-11e9-95a2-d9f83cbc3768.png">

**Comment by christiemolloy** [comment]
@rachael-phillips when should I start implementing the CSS

**Comment by rachael-phillips** [comment]
Hi @christiemolloy we should go ahead and get started on this
