### ISSUE TITLE
Correct nav style unclear

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1250]
There are quite a few places where navigation is demoed/described, but there is inconsistency in how things look and work.
These should be consistent so that teams can reference the correct style.

The react demo of "nav" has selected items with a grey bg and left blue border
https://www.patternfly.org/v4/documentation/react/components/nav/
![Xnip2019-06-20_14-27-24](https://user-images.githubusercontent.com/23172038/59872335-87c10800-9367-11e9-8efc-169517f3738f.jpg)

Versus in the design documentation (and the upcoming designs for mega menu), selected items have no background and have a blue border under them
![Xnip2019-06-20_14-28-07](https://user-images.githubusercontent.com/23172038/59872416-ad4e1180-9367-11e9-8f67-f0b09c9ab788.jpg)

**Comment by rachael-phillips** [comment]
Hi @gdoyle1 is this something we can solve with our symbol library effort?

**Comment by gdoyle1** [comment]
@katierik @rachael-phillips Hi guys. Katie, you are seeing these changes because the website is still pulling in website styles into the components (both react and core). If you check the react workspace here: https://patternfly-react.surge.sh/patternfly-4/components/nav/, you'll see it matches the design guidelines and the core implementation.

Yes this is correctly designed in the symbol library as well!

**Comment by jschuler** [comment]
This should be fixed in production now
https://www.patternfly.org/v4/documentation/react/components/nav/
