### ISSUE TITLE
no background on PF4 login example page

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-org#1270]
The [preview](https://www.patternfly.org/v4/documentation/react/components/loginpage/) has a background image, but the [example page](https://www.patternfly.org/v4/documentation/react/components/loginpage/simpleloginpage/) doesn't.

**Comment by mcoker** [comment]
Looks like this is due to the negative `z-index` on the background image component and the extra `<body>` element added to the page from the example being served in the shadow DOM. We apply a white background color to `body` in PF4, so the background image is rendering behind the extra `<body>` element. If you apply `background-color: transparent;`, to that `<body>` element, the background image works as expected.

Not sure the best approach to fix this. I wonder if the negative `z-index` on that component is necessary. It will be a breaking change if we want to try and remove that though.

@jschuler Is there any way for the shadow DOM to not render the `<body>` element? And if so, what about the `<html>` and `<head>`?

**Comment by jschuler** [comment]
Thanks for investigating this @mcoker ! I was wondering what was happening here. I need the html tag so that font icons properly work. I think the best for now would be to add the transparent background color to the body tag. Does that seem ok?

**Comment by mcoker** [comment]
@jschuler are you able to test a branch of mine that has a fix? I think I can fix the FA issue in core. https://github.com/mcoker/patternfly-next/tree/issue-pf-org-1270

**Comment by jschuler** [comment]
@mcoker i just tested and your changes to fix FA issue works!

**Comment by mcoker** [comment]
@jschuler thanks! submitted a PR in core with this fix. https://github.com/patternfly/patternfly-next/pull/2018

**Comment by jschuler** [comment]
Thanks for reporting @andreasn , this is fixed now
