### ISSUE TITLE
Fix a11y issues in Design Guidelines/Icons

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1292]
https://www.patternfly.org/v4/design-guidelines/styles/icons

There are 4 types of a11y issues in this page:
1. IDs used in ARIA and labels must be unique (popover-bottom-header)
2. Form elements must have labels (add a label to the search box)
3. Heading levels should only increase by one (maybe use a div here if it doesnt affect styling)
4. Sufficient color contrast (For “#primaryIconsSearch”, use the same border color on the search box as we do in input fields (#151515))

<img width="490" alt="Screen Shot 2019-07-17 at 9 08 16 AM" src="https://user-images.githubusercontent.com/20118816/61378058-7ee22a00-a872-11e9-9d70-ff4fd3f0bdf7.png">

Steps to reproduce the a11y errors: 
1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by lareplog** [comment]
@seanforyou23 @jschuler for the first issue, there's about 100 different "popover-bottom-bodies" so would it be better to remove the id or to dynamically generate ids for each popover created?

**Comment by christiemolloy** [comment]
@gdoyle1 @mmenestr did you mean the color #151515 , it shows up like this which seems to dark/not like what we have in Core:

<img width="488" alt="Screen Shot 2019-07-18 at 1 19 55 PM" src="https://user-images.githubusercontent.com/20118816/61478100-d8c01e00-a95e-11e9-867f-9a70ba52d6b2.png">

**Comment by seanforyou23** [comment]
@lareplog I think it's always good to use some sort of semantic text as the id when possible. In this case, it looks like we already have access to a dash-delimited text string (for example "folder-open") that we could recycle for the id as well. This would make automated tests much easier. Otherwise, a generated id will work fine.

Only thing to avoid is removing the id altogether as it's referenced like `aria-labelledby="popover-bottom-header"` which is important so that the popover content is properly related to the content it's attached to.
