### ISSUE TITLE
Fix a11y issues on select page

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1357]
There are 24 color contrast issues at this link https://www.patternfly.org/v4/documentation/core/components/select

"Element's background color could not be determined because it is overlapped by another element"

@seanforyou23 do you know if we can dismiss these issues? I can't determine what is overlapping what.

**Comment by seanforyou23** [comment]
@christiemolloy looks like there's a `background-image` property set to a data url which is sometimes updated to show an icon - in case it's possible, I think the best thing would be to simply use `background-image: none` for when there's no icon to display. Seems sort of strange to set a data url when it's just the white background, even aside from the accessibility side of things. Can we make this change in core? Is there anything to do on the react side?

**Comment by seanforyou23** [comment]
Ohh, it's for the magnifying glass icon (thx for pointing it out @christiemolloy).

<img width="153" alt="Screen Shot 2020-07-06 at 1 39 15 PM" src="https://user-images.githubusercontent.com/5942899/86622821-8bcdc100-bf8e-11ea-8742-b72993d85c24.png">

Since the icon is only a visual artifact and not directly focusable/interactive itself, is there a way we could refactor the HTML so that this bg image is attached to an element that isn't the input element itself? I think that could solve it. If that's not possible or would require breaking change, I'd say its an issue that's safe to ignore as we ensure the text never overlaps the icon with left padding. It does seem to be a reasonable limitation of the tooling, though. Trying to detect this overlap programmatically with the varying fonts, resolutions and PPI density is probably a nightmare.

**Comment by christiemolloy** [comment]
I think this will require a breaking change, right @mcoker ? I would be inclined to say lets ignore the axe issue .
