### ISSUE TITLE
Trend Card: code sample

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#139]
On the [Trend Card Code tab](https://v2-patternfly.rhcloud.com/pattern-library/cards/trend-card/#/_code):
- On the Card with Multiple Trends example, the right-most end point (and presumably current value) for Virtual Disk I/O doesn't look like it's 30%.  Same for Memory Utilization, which should be 22%.
- The numbers (30%, 6%, and 22%) should be left-aligned.
- The label on the action icon should be “Create Cluster” to be in keeping with our T&W.

**Comment by dlabrecq** [comment]
The values for the right-most end point appear to be correct. 

In order to change the label alignment, that would need to be modified in Angular-PatternFly. That is, this would be a change to the component itself. @LHinson we may want to create a story to investigate/fix the component if it's not in spec?

In regard to the new "Create Cluster" icon label, @LHinson we'll need new images. The Angular-PatternFly example can be easily changed to match.

**Comment by LHinson** [comment]
The images are updated. I've filed an issue against angular since this is against the angular implementation and closing here. You can say up to date here: https://github.com/patternfly/angular-patternfly/issues/739
