### ISSUE TITLE
Docs: Experimental and deprecated components on the site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1420]
In this example, data toolbar and toolbar will live on the site together. Here are the notes about toolbar design guidelines from 8/20.

How do we want to name toolbars and how will they exist with design guidelines on the site?

- It could appear as toolbar in the documentation and data toolbar in the folder structure
- Can we address the fact that we will need an inline alert that this is the toolbar, but we have something in experimental that could replace the component?
- On the current documentation it has clarification that it is experimental
- We could create a new section called deprecated 
- Toolbar layout in React is actually a component 
- The design guidelines will continue to point to non-experimental toolbar
- We’ll figure out what the design documentation looks like on the site - experimental needs design documentation
- If we can adopt data table it will simplify a lot of things technically - if we can take that across the board then that will be helpful
- New document of for design guidelines replaces old documentation for data toolbar
- Is there any reason why we would you use the old toolbar?

**Comment by mcarrano** [comment]
You can find a proposal to address this issue here: https://docs.google.com/document/d/1qVwANvTNbHTa0G7WQ8_RKK60lFj7xr9RwHi-6h_HxEQ/edit?usp=sharing  I have also opened a related issue to auto-generate a list of related component links that I think will be needed for long term maintenance of this feature and avoid lots of manual updates: https://github.com/patternfly/patternfly-org/issues/1434

**Comment by mcarrano** [comment]
@rachael-phillips I have created a set of new issues to track this work in the -org repo as follows:

* Add introduction to Experimental Features to the Get Started page on the website that:
** Explains what experimental features are.
** Explains how to provide feedback.
https://github.com/patternfly/patternfly-org/issues/1445 

* Add detailed instructions for working with experimental features to Documentation landing page (new). https://github.com/patternfly/patternfly-org/issues/1446 

* Create a mapping file for all component links in docs to be done via a lookup table. Would allow updates to be done in a single location as items move from experimental to production (avoid need to manually update individual docs). See issue https://github.com/patternfly/patternfly-org/issues/1434 

* Add an experimental features Category in the Forum where users will be directed to provide feedback. https://github.com/patternfly/patternfly-org/issues/1447

**Comment by rachael-phillips** [comment]
Thanks so much, @mcarrano! Adding this to the epic now!

**Comment by evwilkin** [comment]
@mcarrano @rachael-phillips do we think any follow-up is needed on the 3 remaining issues in this epic?  Experimental components no longer live in their own section so their URL does not change when they're promoted from experimental, and soon with the release of the new website redesign all component URLs will be changing due to combining the Core & React docs.

**Comment by mcarrano** [comment]
I feel like these issues can be closed out. @rachael-phillips do you agree?

**Comment by redallen** [comment]
I think we've settled on using banners and including some frontmatter in the component docs that we want to add messages to.

Closing.
