### ISSUE TITLE
Provide parity between workspace docs and website docs

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#1509]
I think the workspace does a nice job of breaking down how to contribute to PatternFly. Since the workspace won't be around forever it would be good to ensure all the docs there make it to the site in the appropriate places.
For example:
https://pf4.patternfly.org/guidelines has lots of good content about SCSS/CSS 
which doesn't exist entirely on the patternfly website here:
https://www.patternfly.org/v4/contribute/developers
There is also 
https://www.patternfly.org/v4/documentation/react/overview/css-variables/
Which should be linked to from the contribute section. We also don't mention BEM on the site (unless I missed it) which I think it something that devs could benefit from quite a bit.

**Comment by rachael-phillips** [comment]
@matthewcarleton can you tell me more about what information you don't want to lose? cc @dgutride @redallen

**Comment by evwilkin** [comment]
@mmenestr @mcarrano making you aware - this may be worth revisiting with all the content changes going in for the website redesign work.

**Comment by redallen** [comment]
@mcoker What top-nav items in Core do you find fit for patternfly.org? Where would you like them to live?

**Comment by mcoker** [comment]
I could see having a link on /contribute/develop that links to the guidelines in both pf4.pf.org/guidlines and pf4.pf.org/contribution - html, css, handlebars, links to how to run the server, how to create new things, etc. But I think those docs need to be updated, we haven't modified them in a while and they may be inaccurate. We could also update with some concepts I've added here in a [doc for new contributors](https://docs.google.com/document/d/1FQSJ4MVsiMr3c6rLxRmJKdqv5D8saVuINDQYFSVXuA4/edit#heading=h.fe3t7h35huj8).

We could probably take a quick pass at those docs and get a rough draft up on the site now, or just start on that rough draft. I also wonder if maybe some of this documentation belongs on github instead of (or in addition to) the website?

**Comment by redallen** [comment]
> Since the workspace won't be around forever

I think it's here to stay for now. If we do remove it we can source the 3 pages without parity (https://pf4.patternfly.org/contribution, https://pf4.patternfly.org/guidelines, and https://pf4.patternfly.org/modifiers) on patternfly.org. For now I think they are specific to HTML development and don't need parity since we don't have an HTML dev landing page.

Feel free to reopen if you think there's a specific section of the site they should be hosted on or linked from.
