### ISSUE TITLE
Provide more robust design guidelines on button usage

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1514]
We should have more robust guidelines on button usage to update: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links

For example, when to use link style vs secondary buttons. Other issues?

**Comment by mceledonia** [comment]
Agreed on the need here, looping back around to the design issue I have a feeling things will be a lot more simple documentation-wise if we have a solid secondary style which covers the cases we are currently using the link styling for. It shouldn't be a breaking change as it would only be color changes, but still worth making sure. 

Without that I feel we will want to commit to one or the other (secondary or link) for most cases, I feel as though our current approach is a mixed bag of secondary and link styling due to the root problem of our secondary button visual styling not being as good as it could be rather than any solid justifications for one versus the other.

**Comment by mcarrano** [comment]
@mmenestr see Michael's comment above.
