### ISSUE TITLE
Add Katacoda training modules to site

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1521]
Now that @dgutride has finished the [spike](https://github.com/patternfly/patternfly-org/issues/1490) we can move on to designing the stories for Katacoda to exist on the patternfly-org site. I quickly drafted some basic wireframes for how they should lay out.

The training should exist under Documentation. 
- For React tutorials they should exist under the "React" framework > "Overview" > "React Training"
- For HTML/CSS tutorials they should exist under the "HTML" framework > "Overview" > "HTML/CSS Training"

For React training, tutorials should be categorized between:
- React fundamentals
- React components (table etc.)
- React charts

For HTML/CSS training, tutorials should be categorized as one component unit: HTML/CSS Fundamentals

When the "start" button is clicked for a tutorial it should link to a new page within the patternfly website where the iFrame is embedded, and the side menu of the website should be hidden to allow more room for the tutorial. We think we might use breadcrumbs at the top of the tutorial so that the user can navigate.

Potentially we could also recommend tutorials underneath the current tutorial, that are similar.

![katacoda-artboard-1](https://user-images.githubusercontent.com/20118816/67497102-78bad100-f64b-11e9-9734-4f50b6f7131c.png)
![katacoda-artboard-3](https://user-images.githubusercontent.com/20118816/67497105-78bad100-f64b-11e9-866d-9b61ba11e81c.png)
![katacoda-artboard-2](https://user-images.githubusercontent.com/20118816/67497104-78bad100-f64b-11e9-8b23-dda7acd2a4a0.png)

**Comment by rachael-phillips** [comment]
@dgutride @christiemolloy @gdoyle1 @LHinson I wanted to summarize what Christie and I discussed yesterday about the Katacoda tutorials design and where it will live.

- The tutorials homepage will be a card design that lives under Overview in Documentation.
- We discussed that in order to stay consistent across RH site experiences we should mimic the flow and approach that the Developers site took to embedding the tutorials. 
- The tutorials should not be embedded with the site header header attached, and should instead should take the user to "another place" and should mimic the pattern on the Developers site.
- For the Katacoda tutorial that will be helpful in getting started for HTML/CSS or React it should be placed as a text link within the Get Started for Developers page (not a card) The link should take you to the Katacoda tutorial homepage. This trains the user as to where to access the Katacoda tutorials in the future and aids discovery of other tutorials.
- At the bottom of the Getting Started page for developers, we should ask "Looking for a deeper dive into PatternFly? Check out more of our tutorials to get up to speed." Which should link to the tutorials homepage.
- For the component specific tutorials like Table that should also exist as a textual link which will take you to the tutorials homepage.

Please let me know if you have any questions or concerns about this approach!

**Comment by gdoyle1** [comment]
Still working on these designs but here's the Marvel project: https://marvelapp.com/4ih2jjj

**Comment by gdoyle1** [comment]
@christiemolloy I added the spec for the cards to the HTML/CSS training page here: https://marvelapp.com/4ih2jjj. Let me know if you have any questions!
