### ISSUE TITLE
Page layout demos - Codesandbox link gives error

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1555]
Clicking on the codesandbox links on the [page layout demo page](https://www.patternfly.org/v4/documentation/react/demos/pagelayout) opens codesandbox but it hangs on “Resolving Dependencies…” and is showing an error.

**Comment by ddonahue007** [comment]
The fix for this specific error is in the following PR - [2549](https://github.com/patternfly/patternfly-next/pull/2549)

There are still issues with missing imports through out the page demo. I am fixing those as part of the PR as well.  

There is also an issue with both '/imgBrand.png' and './imgAvatar.svg' not being loaded automatically to Codesandbox.  This is a short coming of codesandbox.
