### ISSUE TITLE
Vertical Navigation: Tooltip missing within design spec

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#164]
The "Collapsed Primary Navigation without Icons” section of the vertical navigation is missing a tooltip icon on the design

**Comment by dlabrecq** [comment]
@LHinson Need a new image here.

**Comment by LHinson** [comment]
@lizsurette I'm not seeing a tooltip on the navigation with icons. In order to match the design spec, we definitely need a tooltip there so the user knows what those icons are when names are collapsed. I don't think we need a tooltip on the navigation without icons. Unless I'm missing something? Thanks for clarifying :)

**Comment by LHinson** [comment]
Checking back on this one and seems to be addressed. I see the tooltips on hover of the icons so I'm closing this issue.
