### ISSUE TITLE
Reconsider presentation of Experimental Features

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1646]
Reconsider the presentation of Experimental Features on the website to address the following problems:

* Experimental features are currently difficult to find. We would like to explore a way to move them back into the components category with some unique tagging.
* Messaging around experimental features is vague and potentially misleading. There is nothing that explains what an experimental feature is or how to provide feedback other than the warning message placed at the top of the component page. This may lead consumers to believe that they should not be using these features. Want to replace this with an Overview page and less intimidating messaging.

**Comment by rachael-phillips** [comment]
@dgutride @seanforyou23 please add any info you would like here. We would like to add the ability to indicate an experimental example or prop, as well.

**Comment by seanforyou23** [comment]
Right, there are experimental components, and then we could also have experimental features of production-ready components. Experimental features can easily involve many touch points across many components. For example, with inline edit we have several new props for BodyCell, new props for Table, several new utility functions, some new types/interfaces, and a couple of new components like EditableColumn and EditableTextCell. As you can see, just one experimental feature can consist of many new api parts across several modules. Not sure the best way to represent this visually, but figured I'd mention to give an example of something we have in the works right now. Let me know if I can provide any other information that may be helpful!

**Comment by rachael-phillips** [comment]
Development recommendations: https://docs.google.com/document/d/1x9bCDcCa7Sw5gEQj1aeWJUNQ5tNjysyfi-tEz91-p9U/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Hi @dgutride @LHinson @mcarrano would love your review on our New Beta badge design. I have also added some copy that should represent which a Beta badge is. I would love your review on the copy and design.

The design includes:
1. A badge placed on the sidebar to represent it is Beta
2. The badge then placed on the component page under the title for visual continuity and affordance
3. The badge then placed at the example level (as an example for where the Beta badge would be placed for an example)
--Below the fold, if you scroll down a lot--
4. The badge then placed at the prop level (as an example for where the Beta badge would be placed for a prop)

I would really appreciate your review, and please indicate in your review your preference and why. My preference is option 2. because it has the most consistency with the rest of the styling on the site. **In response to this change I would like to update non-link blue text across the flow, so that this text does not look like a link.**

https://marvelapp.com/85353b9

**Comment by rachael-phillips** [comment]
We will also need to update badges across the flow. For example, this badge will need to be updated to match new styling:

<img width="1482" alt="Screen Shot 2020-02-03 at 11 20 37 AM" src="https://user-images.githubusercontent.com/40275806/73670584-7a972600-4677-11ea-8f82-0f4abad81262.png">

**Comment by mcoker** [comment]
I like either 1 or 2. I like 1 because it's a little more prominent but I don't feel strongly about it. 

I wonder if the badge should be adjacent to the component title, and also next to the nav item text, like this:

<img width="745" alt="Screen Shot 2020-02-03 at 2 19 44 PM" src="https://user-images.githubusercontent.com/35148959/73687736-4e3bd380-4690-11ea-9d19-efa83e8300cb.png">

<img width="918" alt="Screen Shot 2020-02-03 at 2 14 29 PM" src="https://user-images.githubusercontent.com/35148959/73687760-55fb7800-4690-11ea-8e5e-298aea89fa47.png">

**Comment by mcarrano** [comment]
I think that the mocks look good @rachael-phillips . I could go with either options 1 or 2. Option 2 would require a new variant of the Badge component as we don't have that styling right now. I just spoke with @maryshak1996 about looking at our overall approach to labels and badges, so she might offer some visual input here. Just a couple of other comments:

* When the entire component is "beta", I question whether we need the badge both in the navigation and at the top of the page. This seems a little redundant. If we do keep in the page header, suggest adding it to the right of the component name rather than below for consistency with how it's used elsewhere.
* I think the text is good, but maybe box that in an info alert like we have for experimental features now?
* If a production component contains beta features, would we consider adding a message at the top that says something like, "This component contains beta features that are currently under review, so please join..."?

**Comment by rachael-phillips** [comment]
Thank you for the feedback @mcarrano! This is great! I can tie all of your feedback together in one design. Here it is:

![Updated screen with alert](https://user-images.githubusercontent.com/40275806/73765410-826fcc80-4742-11ea-80e4-1e54a3d0b314.jpg)

**Comment by mcarrano** [comment]
Looks great. Thanks for making the updates @rachael-phillips !

**Comment by rachael-phillips** [comment]
@dgutride and @LHinson could you give the latest design posted a review? Earlier iterations are linked in the Marvel mock-up.

**Comment by rachael-phillips** [comment]
Hey @mcarrano I'd like to update the design recommendation above. I don't think we actually need the Beta labels in the left nav. As I've been doing this competitive analysis, I've taken a look at what Material as I've been doing this competitive analysis. Nothing in the nav here, just in the body. Do you have any concerns about this change in the design?

<img width="1593" alt="Screen Shot 2020-02-05 at 2 45 18 PM" src="https://user-images.githubusercontent.com/40275806/73877595-f388b000-4826-11ea-8aa0-ee9c3f405aa7.png">

**Comment by mcarrano** [comment]
I think this is OK @rachael-phillips Can't think of a good reason this needs to be visible from the Nav

**Comment by rachael-phillips** [comment]
Here is the updated design: 

![jkh](https://user-images.githubusercontent.com/40275806/73947499-8e37cc00-48c5-11ea-9419-e63fa80541ed.jpg)

**Comment by mcarrano** [comment]
Looks great @rachael-phillips !

**Comment by mcarrano** [comment]
Looks like this work is completed so I will close this one out.
