### ISSUE TITLE
Bug - Code Sandbox broken on tooltip examples

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1791]
For react tooltip examples, the code sandbox is broken.
![Xnip2020-04-15_13-51-26](https://user-images.githubusercontent.com/23172038/79370171-37332080-7f20-11ea-9824-998bc9962388.jpg)

**Comment by evwilkin** [comment]
Thanks for filing this bug @katierik !

**Comment by redallen** [comment]
PR up to fix it :)

**Comment by katierik** [comment]
Found another place this is broken: 
https://codesandbox.io/s/e4s1h

Donut chart examples
https://www.patternfly.org/v4/documentation/react/charts/chartdonut

**Comment by redallen** [comment]
Nice find @katierik ! This issue is twofold -- we need to not `import "@patternfly/react-core/dist/styles/base.css";` for example that don't use react-core, and we need to change:
```js
const SmallWithRightLegend = (...)
```
to
```js
const SmallWithRightLegend = () => (...)
```

The first change needs to happen in patternfly-org, and the second in patternfly-react. We'll prioritize this after breaking change work.
