### ISSUE TITLE
Add Hover specifications for icons

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#1826]
Clickable icon colors are not specified on the [buttons/icons page](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links#icon-button) or the [colors page](https://www.patternfly.org/v4/design-guidelines/styles/colors#typography-and-iconography-colors).

Explicit guidance would be helpful here for implementation and QA teams.

**Comment by gdoyle1** [comment]
@Rohoover Agreed! We are updating the icons page to look like this: https://marvelapp.com/dj2867b. Let me know if there's enough guidance on that redesign that covers your needs. Otherwise we have _some_ guidance on it on the colors page...
<img width="504" alt="Screen Shot 2020-04-30 at 10 40 54 AM" src="https://user-images.githubusercontent.com/30870144/80723817-1695c980-8acf-11ea-8712-3f84df1c4e5d.png">
<img width="510" alt="Screen Shot 2020-04-30 at 10 40 50 AM" src="https://user-images.githubusercontent.com/30870144/80723818-172e6000-8acf-11ea-8792-98bb44fbd0b9.png">

**Comment by evwilkin** [comment]
@Rohoover @gdoyle1 with the recent updates to the website is there still follow-up needed here?  Here are the [icons](https://www.patternfly.org/v4/guidelines/icons) and [colors](https://www.patternfly.org/v4/guidelines/colors) pages for reference.

**Comment by evwilkin** [comment]
Closing out per comments above, if additional work is needed please feel free to reopen.
