### ISSUE TITLE
Add Call to Action to Button design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1841]
Update design guidelines document here to include usage guidance on the Call to Action button variant: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links

More design background can be found here, the guidelines are almost already written for you: https://github.com/patternfly/patternfly-design/issues/803

"Call to action buttons and links are used on websites to direct users to a complete an action. An example would be an informational page about a product with a "Try it now" call to action button. They differ from primary buttons and links as a highly visible way to indicate a desired next step whereas buttons and/or links may be used elsewhere on the page to link to additional info or actions. Call to actions should be used sparingly, ideally 1 per page or a primary and secondary CTA."

**Comment by mmenestr** [comment]
Can assign this

**Comment by mmenestr** [comment]
@mcarrano Commenting here since this is already an issue for editing the button guidelines, but I noticed that we may need to change the button guidelines a little because it says that the spacing between two buttons should **always** be 16px, but that doesn't seem to be the case for modals, who seem to have 8px spacing? And I seem to remember another instance where you updated a guideline and the spacing was only 8px, I think for toolbars? I feel like these exceptions or distinct cases should be addressed in the button guidelines...

**Comment by mcarrano** [comment]
@mmenestr I agree. It's not as simple as we state in this document, and we should call out or detail some of these exceptions.

**Comment by beccaglass** [comment]
@mmenestr @mcarrano copied existing google doc and added to it: https://docs.google.com/document/d/1CVuK7_uBEwTwrjdKGI-LsVu37Yh5A2t_qdKpF_nH46I/edit?usp=sharing

New sections are highlighted in yellow. Added a CTA section under button types added new sections for spacing exception cases. Can provide images & markdown if all looks good.
