### ISSUE TITLE
Broken image links 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#213]
Was looking through the PatternFly blog history to see if I could find a blog about how to do required fields in forms, and I stumbled across this blog where all the image links are broken:  https://blog.patternfly.org/drill-down-looking-into-details/

**Comment by dlabrecq** [comment]
Looking at the image source below and the image no longer exists. Someone will need to update this blog post with the correct images.

﻿&lt;img class="alignnone wp-image-5470 size-full" **src="https://www.patternfly.org/wp-content/uploads/2016/01/list-view-e1453129387701.png"** alt="list view" height="581" width="1400">

Not sure why the image path is pointing to the old patternfly web site. The blog is also a WordPress site and expect the images could have been uploaded there?

**Comment by LHinson** [comment]
@henqian can you help with this?

**Comment by henqian** [comment]
@LHinson @dlabrecq  I uploaded the images to the Media Library again and now it looks like the original. You can see the blog at: https://blog.patternfly.org/drill-down-looking-into-details/

Let me know if there is any other thing I can help with. I am not sure what caused the problem. Maybe someone deleted the images since they look irrelevant, maybe we didn't migrate everything when we moved to new version of PatternFly?

**Comment by dlabrecq** [comment]
The originals appear to have been uploaded to WordPress via www.patternfly.org, which is no longer valid after the site upgrade. We shouldn't have any trouble now that they have been uploaded to blog.patternfl.org.

**Comment by LHinson** [comment]
@dlabrecq @henqian awesome, thanks for addressing this!

**Comment by LHinson** [comment]
Closing since this was addressed. Thanks :)
