### ISSUE TITLE
Clarify which font files to use on typography page

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#2261]
https://www.patternfly.org/v4/guidelines/typography

Is it helpful to clarify the different between RedHatDisplay at a medium font weight (400) and RedHatDisplay-Medium?
I came across an issue that the rendered font was RedHatDisplay 500wt, which is thinner than RedHatDisplay-Medium 400wt.

**Comment by ajacobs21e** [comment]
Separate issue but still typography page - should we explicitly say "Red Hat Display should only be used for headlines, Red Hat Text only used for body copy"? I got that question from someone in marketing. While you can deduce that from the examples, it's not explicitly stated.

**Comment by mmenestr** [comment]
@mcarrano do you know if what Allie stated in her comment is true? I believe it is but wanted to double check

**Comment by mcarrano** [comment]
@mceledonia see above. Can you confirm?

**Comment by mceledonia** [comment]
@mmenestr @mcarrano Yes that is true. Red Hat Display is for larger text headlines, whereas Red Hat text is made for body text with better long-form readability. Important to this distinction is that it is more about size than usage. I think smaller subheaders (for example subheaders of a grouped list) should still be Red Hat text because it reads better at smaller sizes.
