### ISSUE TITLE
Gatsby theme upgrade path

### ISSUE THREAD

**Issue by tumido** [patternfly/patternfly-org#2312]
Hi team,

we're pretty heavy Gatsby users in our organization and we're investigating possibilities to move out from our custom made "shared components" towards using a Gatsby theme. My question is, which package would be the best to start with and what is the expected Patternfly 4 upgrade path for those. I've looked up all these npm packages:

- [theme-patternfly-org](https://www.npmjs.com/package/theme-patternfly-org)
- [gatsby-theme-patternfly-org](https://www.npmjs.com/package/gatsby-theme-patternfly-org)
- [gatsby-theme-patternfly](https://www.npmjs.com/package/gatsby-theme-patternfly) - from @jschuler  https://github.com/jschuler/gatsby-theme-patternfly/issues/15

Yet neither of those seems up to date with patternfly desing - especially when it comes to Patternfly v4 support. All of them suggest to use fairly out of date Patternfly react packages.

Is any of those packages the go-to theme to use if we want to use Patternfly on our Gatsby websites or do we have to build our own? Do you have any usage docs or what would be the right course of actions. 

On behalf of https://github.com/AICoE and https://github.com/operate-first organizations

**Comment by evwilkin** [comment]
We've moved away from Gatsby for our docs, but @redallen had a big part in implementing with Gatsby and may have some thoughts or feedback around this.

**Comment by redallen** [comment]
Sorry for the late response @tumido .

@jschuler 's [gatsby-theme-patternfly](https://github.com/jschuler/gatsby-theme-patternfly) is what you're looking for, but unfortunately it's not officially supported by PatternFly and is also out of date.

For a time we used `gatsby-theme-patternfly-org` as a theme for our docs to share which was deprecated in favor of `theme-patternfly-org` which ditched Gatsby entirely for a leaner and meaner custom build system. Since we no longer use Gatsby (and no Red Hat products do) we currently do not support Gatsby.
