### ISSUE TITLE
Links to Sketch design template and Library files broken

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2345]
The links to content on Sketch Cloud (template and library files) on Get Started page for designers are no longer working (https://www.patternfly.org/v4/get-started/design).

cc @evwilkin

**Comment by mcarrano** [comment]
@doruskova I opened this new website issue and assigned it to you. Can you investigate what happened and identify updates we may need to make? I will be happy to put up a PR for this if you want.

@evwilkin We just discovered these broken links today and suspect that Sketch changed something. Will definitely want to clean up for the next website release.

**Comment by doruskova** [comment]
@mcarrano It looks that links on a PF website have a short URL that is no longer supported. If you are logged in to Cloud and use a short URL to visit a document you have access to, you should be redirected to a longer URL. That's why it works for me because I'm usually logged in to Cloud. It means that we need to use these longer links to our website: 

- Library: https://www.sketch.com/s/2cf1063b-5283-4e0b-b8a6-cbb1ac07e29e
- Template: https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89

Here's what I found :) 
<img width="676" alt="Snímek obrazovky 2021-01-11 v 9 21 22" src="https://user-images.githubusercontent.com/32618096/104158874-8b572c80-53ee-11eb-8287-3b249421abec.png">

<img width="608" alt="Snímek obrazovky 2021-01-11 v 9 21 02" src="https://user-images.githubusercontent.com/32618096/104158887-9447fe00-53ee-11eb-99e4-546be4a5d455.png">
<img width="1096" alt="Snímek obrazovky 2021-01-11 v 9 21 34" src="https://user-images.githubusercontent.com/32618096/104158928-b04b9f80-53ee-11eb-9fff-4f1ac07e3e31.png">
