### ISSUE TITLE
Hierarchical [inline] alerts/indicators

### ISSUE THREAD

**Issue by manstis** [patternfly/patternfly-org#2387]
Many applications provide validation of their content.

Many applications support hierarchical content.

It can be difficult for Users to determine what nested hierarchical content may be invalid.

A workaround is to provide a tree type component of all content and flag nodes in the tree as having errors.

Not all applications want a tree.

We (RH engineering) have been referred to PF "inline" alerts and OpenShift design guidelines:

- https://www.patternfly.org/v4/components/alert#inline-types
- http://openshift.github.io/openshift-origin-design/conventions/documentation/alerting.html
- http://openshift.github.io/openshift-origin-design/designs/administrator/4.4/notification-drawer/

None of these support indicators to nested validation issues.

e.g. indicators in tabs, indicators in navigation buttons, indicators in Data List rows etc.

[Feedback](https://drive.google.com/file/d/1IK8vEG4M7a7GuI3_OVH7uIwR5Dxy40xx/view?usp=sharing) we've had from Users of OpenShift is that it can be difficult to find errors.

We are therefore proposing support for indicators in navigation components.

**_"Top level" - Button shows nested errors_**

![Indicators 1](https://user-images.githubusercontent.com/497544/104897675-9242e980-5970-11eb-8e12-1f1650a0e657.png)

**_"Top level" - Tooltip example (could be popover etc)_**

![Indicators 2](https://user-images.githubusercontent.com/497544/104897677-92db8000-5970-11eb-9419-b2d385ffef57.png)

**_"Nested/intermediate level" - Row shows nested errors_**

![Indicators 3](https://user-images.githubusercontent.com/497544/104897679-92db8000-5970-11eb-897f-482a41f00ae0.png)

**_"Bottom level" - Normal PF field validation_**

![Indicators 4](https://user-images.githubusercontent.com/497544/104897680-93741680-5970-11eb-8b89-3146325f52a1.png)

**Comment by lclay2** [comment]
@mcarrano , @amysueg , @manstis I'm not sure if this is simply a documentation issue, but guidelines would be great so that's for sure! 

My understanding was that for Scorecard this is a stop-gap solution on the way to using the Alerts Notification drawer (as OS does) as the ideal solution. The alerts drawer would allow the user to navigate directly to the issue without having to follow a breadcrumb trail of alerts to get to the same point.  The drawer solution is nice because it would take less time and clicks for the user to get to the same place. And it could also prevent some user frustration if they get "lost" on their way to following this alert trail to its final destination. So do we want to codify and "bake-in" this solution if it's a stop-gap? If it is indeed a stop-gap (one off) solution, @mcarrano , do these things typically go straight to being codified in PatternFly without other product use cases or examples - or is that what the documentation effort will unearth? Fyi. We are looking into doing a usability study of the scorecard POC, maybe it would be helpful to get those results first, if time allows.

**Comment by mcarrano** [comment]
@lclay2 I would be in favor of waiting to see your usability test results before taking an action in PatternFly. Sounds like you have a workable solution for now, so from my perspective there's no rush to add this to the documentation.

@mmenestr let's keep this open, but I will tag it as 'on hold'.

**Comment by lclay2** [comment]
sounds good to me @mcarrano

**Comment by mcarrano** [comment]
Going to close this out following checkin with Missy Johnson. If this is still a need we can reopen.
