### ISSUE TITLE
Add guidelines to forms and modals about focusing on the first field

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#2500]
We don't currently have any guidance on when we should (or if we should) focus on the first field within a form or form within a modal. There are also circumstances where maybe we should be focusing on the cancel button in a destructive action (as [the guidelines in cloud.redhat.com say to do](https://docs.google.com/document/d/1Q58potYqoKfHSjzKY4yW-oUv_ESckI-vsbFnKp0cz3s/edit#)). I _think_ this type of documentation belongs at the PF level rather than leaving it up to products.

Add this guidance to the **modal guidelines**, about which buttons to focus on, and when.

**Comment by mmenestr** [comment]
Focus on modal buttons for this one. When should the focus be placed where depending on the type of modal.

**Comment by bmignano** [comment]
I tried to dig into this a little more, and it seems like there isn't necessarily a strong consensus on recommending autofocus or not with regards to accessibility. I've found a lot of sources citing search engines as a good example of when autofocusing on a field is fine, since searching is pretty much the sole action a user wants to take there. In other cases, it sounds like autofocusing ends up being a nuisance to users with screen readers because they may be dropped somewhere without any context.

Based on https://github.com/patternfly/patternfly-react/issues/4018, we could follow suit with Mozilla and recommend something along the lines of their guidelines:

> For dialogs that only provide a basic message, it could be an "OK" button. For dialogs containing a form it could be the first field in the form.

This could work well assuming that the screen reader reads all the content of the modal first, and the user isn't just dropped into a modal with the option of accepting before hearing what they are accepting. If we follow this guideline, I also wonder whether the autofocus guideline belongs in the Form component guidelines, instead of or in addition to, these guidelines.

And then maybe we add another guideline for confirmation modal of destructive actions, such as 'Focus on the cancel button or 'X''.

Definitely a bit of a tricky one; what do you think @mmenestr @jessiehuff ?

**Comment by mmenestr** [comment]
@bmignano I think what you're suggesting sounds great! We could add something on this in both the modal and form guidelines. but @jessiehuff I am curious to hear your thoughts too!

**Comment by jessiehuff** [comment]
This is definitely a great discussion to have and one I've been thinking about myself. I do think that PF needs a better example of the scenario that you're talking about, and I [created an issue to do that here](https://github.com/patternfly/patternfly-react/issues/6235), though the goal of that one was a combination of modals, forms, and alerts and how they fit together/interact. Typically when it comes to focus management in a modal, we've tried to follow the WAI ARIA Authoring practices that explain a modal's focus [here](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal).
In the notes section:

1. When a dialog opens, focus placement depends on the nature and size of the content.
- In all circumstances, focus moves to an element contained in the dialog.
- Unless a condition where doing otherwise is advisable, focus is initially set on the first focusable element.
- If content is large enough that focusing the first interactive element could cause the beginning of content to scroll out of view, it is advisable to add tabindex=-1 to a static element at the top of the dialog, such as the dialog title or first paragraph, and initially focus that element.
- If a dialog contains the final step in a process that is not easily reversible, such as deleting data or completing a financial transaction, it may be advisable to set focus on the least destructive action, especially if undoing the action is difficult or impossible. The Alert Dialog Pattern is often employed in such circumstances.
- If a dialog is limited to interactions that either provide additional information or continue processing, it may be advisable to set focus to the element that is likely to be most frequently used, such as an OK or Continue button.

With those recommendations in mind, we've always focused the first focusable element inside the modal (in every PF example, I think this is the close button which also could be argued as the least destructive). I recently worked on a11y documentation to explain a11y for as many components as I could, and the modal docs are [here](https://www.patternfly.org/v4/components/modal/accessibility). There I mention that focus should go on the first focusable element, but I definitely think there's room for improvement to discuss different scenarios. I'm open to suggestions on any and all of these!
