### ISSUE TITLE
icon color guidance

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#2507]
https://www.patternfly.org/v4/guidelines/icons#icon-colors links to https://www.patternfly.org/v4/guidelines/colors#text-and-icons which doesn’t really explain what colors to use for icons. 
Some guidance which would be helpful to document is when icons should be black or grey. From Michael:
Actionable icons (can click/tap them to perform an action) are a dark grey which turn black on hover. Non-actionable (decorative, including icons with tooltips or icons within an actionable element such as button) are always black. 

This may be a separate issue @doruskova that some icons in the sketch library are grey and some are black. Maybe if we made them all the same color it would help?

**Comment by doruskova** [comment]
@ajacobs21e Agree that the guideline doesn't explain what colors to use. I don't have any problem changing the color to black even if I understand why some of them are grey. This change makes sense to me because sometimes you have to use a different icon, not from the actionable (grey) section, and make it grey anyway. I'm just a little bit concerned about what's gonna happen after this change :D I'll try to make a change offline to see the result. It'll definitely take some time to review all symbols and check the template file as well. Also, I'm wondering if we can change the color of the dynamic icon directly to black instead of having an additional color layer applied to this icon.

**Comment by ajacobs21e** [comment]
@doruskova the dynamic icon doesn't make sense to use anymore I don't think. @cshinn made it because of some limitation in Sketch where we couldn't use color layers or something. Maybe Chris remembers the exact problem. But whatever it is, that problem is gone now. I think it's just more confusing to have two ways to add an icon.

**Comment by edonehoo** [comment]
Closing -- since this issue was opened, our icons guidance has evolved and included some of this information. If guidance is still missing from our site, we can open a new issue to track those updates. Let me know if you have any concerns or questions!
