### ISSUE TITLE
Add to tree view guidelines with enhancements

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2538]
Want to add mentions of new tree view variation to the guidelines.
I believe this is called "Compact tree view" where you have the ability to collapse sections?

Refer to this design issue for details: https://github.com/patternfly/patternfly-design/issues/1043
See marvel here: https://marvelapp.com/prototype/73043j4/screen/80030545
Core: https://github.com/patternfly/patternfly/issues/4177

**Comment by mmenestr** [comment]
@doruskova @mcarrano do you mind giving me more background on this issue? Like what the use case for this was, and if it's just about adding in "collapsable" sections to a tree view?

**Comment by doruskova** [comment]
@mmenestr This is the original issue https://github.com/patternfly/patternfly-design/issues/994
It was about spacing that needed to be more compact because OpensShift wanted to show a tree view in a sidebar/drawer. The lines represent tree hierarchy and the requirement was not to show the leaf item only as a text. That's why they requested the lines. Hope it helps a little bit.

**Comment by mmenestr** [comment]
@doruskova would you be willing to take on this design guideline issue actually, since you did the design? Thinking it wouldn't be too time consuming

**Comment by doruskova** [comment]
@mmenestr Sure thing! :)
