### ISSUE TITLE
Add guidance on using disabled tabs

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2637]
Add to tab guidelines to discuss usage of disabled tabs.
Use when someone doesn't have permissions to view something

**Original design request with info:** https://github.com/patternfly/patternfly-design/issues/1066
**Design issue:** https://github.com/patternfly/patternfly/issues/4257
**Related core issue:** https://github.com/patternfly/patternfly/pull/4278

**Comment by lclay2** [comment]
@mmenestr - Here's a first pass, please let me know what you think, thanks.

"Disabled tabs

PatternFly supports a disabled tab variation. A disabled tab indicates that a section either does not have content, or it is unavailable to the user. 

The intended use case is when a user is disallowed from viewing content due to lack of permissions. Information to explain why the tab is disabled may be provided by using a tooltip on the element. "
