### ISSUE TITLE
TypeScript examples parser does not recognize optional chaining syntax (`foo?.bar`)

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#2640]
I'm getting a `SyntaxError: Unexpected token` when trying to use [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in my TypeScript example files.

**Comment by mturley** [comment]
cc @redallen

**Comment by redallen** [comment]
[Optional chaining](https://caniuse.com/?search=optional%20chaining) is not a part of ES2017 which is what our examples currently target. If you grep through all PattenFly example code, none of it currently uses optional chaining. This syntax error occurred before adding TypeScript support; the only relation to TypeScript is that TypeScript versions since 2018 support optional chaining.

While it's a cool feature supported by 91% of browsers and TypeScript/babel-preset-env since 2018, I think it wise to target a single spec (which is currently ES2017). I'm open to arguments for a more recent spec version or statistics on PatternFly consumer tooling to target.

**Comment by mturley** [comment]
Ok, that makes sense to me. In that case I wonder if we can change the linter or tsconfig to disallow usage of it and formalize the fact that it's not allowed in our source currently? I'll look into that. Leaving this issue open for now, let me know if you'd prefer I close it and open separate issues for this.

**Comment by redallen** [comment]
It's allowed in PatternFly source code (which uses a recent TypeScript verison and transpiles to ES2015), but not example code.

I suppose the "linter or tsconfig" is really just the example breaking if you try it.

**Comment by mturley** [comment]
Fair enough. Thanks.

**Comment by mturley** [comment]
Closing this for now. I'd love to have some way to tell VS code to yell at me for using this syntax in PF examples only, but that's overkill.
