### ISSUE TITLE
Add guidance on using tabular font-face

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2760]
Design issue: https://github.com/patternfly/patternfly/pull/4476#issuecomment-976771376

"Want to promote the new tabular font-face as the preferred choice to use when displaying tabular data."

@mcarrano could you add more detail around this, and where this would live? Do you imagine it would live in the table guidelines, or in the text guidelines, or in the typography page?

**Comment by mcarrano** [comment]
I don't know. I'm thinking maybe the Typography page? But could also make sense in the Table guidelines.

**Comment by mmenestr** [comment]
Do not currently use tabular font-face, but want to explore whether we should, and if so, when we should.

**Comment by mcarrano** [comment]
@kelseamann here is the design issue that accompanies that: https://github.com/patternfly/patternfly-design/issues/1140 It provides a bit more background. When you have some specific recommendations, we can review them together. I will also want to get @mceledonia in the loop. Thanks for taking this on.

**Comment by kelseamann** [comment]
Move documentation to new "Patterns" section on a Tabular numbers page. Include some mockups for typical places where we recommend using tabular numbers. Later on, we will create some demos that help both designers and developers understand how to use this feature of the Red Hat font. Some use cases I've outlined through research are:

- Tables and columns
- Dynamic labels with animation (counting up, counting down)
  - For example, time on a music or podcast counting up or down
- Downloading or uploading, progress %

**Comment by kelseamann** [comment]
@mcarrano @mcoker Quick question for you- as I'm working on the demos for this issue, I'm finding that most of the use cases for the tabular font face are within our own components. Generally the tabular font face should be used in cases where numbers are counting up and down so that the differing widths don't disrupt vertical alignment (for example an 8 digit is wider than a 1 digit). Some cases where this is applicable would be in the progress bar, slider, and timestamp, where numbers are dynamic. Other cases could be where numbers are stacked, such as within a table column, again to preserve vertical alignment. 

**My question is this- instead of writing these guidelines, does it make sense to do an audit of where to implement tabular numbers in Patternfly, do so, and then promote those cases?** I can't find any case for using tabular that the user would customize- they are all within components. [More background and visual examples here](https://docs.google.com/document/d/1KpJ13lsDDQ13rz5g09HoTLLBDg5Qgoq0Fa6I8AACg7o/edit?usp=sharing)

**Comment by kelseamann** [comment]
@mcarrano it's tricky because if the numbers are all stacked, the guidance would be to use tabular numbers. So we could set that as the default. It would be an effort to reduce mental load on the user's end of deciding what is tabular and what is not. For example, stacked digits qualify for tabular, but digits + words, like "2 days ago" would not be tabular; setting those fields for them would help reduce mistakes.

**Comment by kelseamann** [comment]
@mcarrano I can bring these up with some visual representation in design share tomorrow?

**Comment by mcarrano** [comment]
Yes, absolutely!

**Comment by mmenestr** [comment]
Issues made in other repos to address this so closing
