### ISSUE TITLE
Optional Chaining can't be used in examples/demos

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#2802]
When attempting to use optional chaining in examples/demos the live preview throws a `SyntaxError: Unexpected token` error at the location of the question mark.

Identified in patternfly/patternfly-react#6725

**Comment by evwilkin** [comment]
This issue is caused by restricting `acorn` (parser used by Typescript) to [`ecmaVersion: 2018` in acorn.js](https://github.com/patternfly/patternfly-org/blob/main/packages/ast-helpers/acorn.js#L12).

Updating this to `2020` ([docs here](https://github.com/acornjs/acorn/blob/master/acorn/README.md#interface)) resolves the issue and allows optional chaining but may have other considerations:

> This influences support for strict mode, the set of reserved words, and support for new syntax features.

Another possible workaround is [acorn-optional-chaining](https://www.npmjs.com/package/acorn-optional-chaining).

**Comment by mturley** [comment]
Once this is fixed it might be nice to go through the examples and convert other defensive coding like `foo && foo.bar` or trivial `if(foo) { foo /* ... */ }` to use optional chaining instead!
