### ISSUE TITLE
Broken Sketch links (Overpass library) on a Design page

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-org#2861]
https://github.com/patternfly/patternfly-design-kit/issues/511

This section https://www.patternfly.org/v4/get-started/design#looking-for-the-overpass-design-kit
has broken links to our old libraries with Overpass font. 

The correct links are: 
Library: https://www.sketch.com/s/65cbc171-3b00-4bc7-b7ff-18e9a5b35ba8
Template: https://www.sketch.com/s/2987fea0-aaee-4e44-9974-5612c949aef0

cc @mcarrano

**Comment by mcarrano** [comment]
@doruskova I wonder if we even need to continue to expose this from the website. It's been quite a while since we switched to the Red Hat font and I feel like whatever is in the Overpass version would be horribly out of date by now. Should we just remove this information?

@mmenestr @mceledonia interested in your thoughts.

**Comment by doruskova** [comment]
@mcarrano I wouldn't remove it because someone who reported this issue apparently looked for the old library and a template file. I also added the [old files to a design kit repo](https://github.com/patternfly/patternfly-design-kit/tree/master/PatternFly%204%20Overpass%20-%20old).

**Comment by doruskova** [comment]
@mcarrano I contacted the designer who reported this issue and he replied that he didn't need it because he works with Red Hat's digital design system. Then, I change my opinion and we can remove it and just keep the old files in a design kit repository.
