### ISSUE TITLE
Add content section in switcher design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2870]
Right now there is some confusion around what the wording should be on a switch label.
Would be great to add some guidance around that!

https://www.patternfly.org/v4/components/switch/design-guidelines

cc: @abigaeljamie

**Comment by abigaeljamie** [comment]
Thank you for creating this, @mmenestr ! I'm going to give this one to @kaedward . Katie, we can chat more about this issue at our content huddle on Friday, but in general, we're looking to add guidance to PatternFly's "Switch" component design guidelines about writing microcopy for switches ("toggles"). The goal is to write messages that make sense when you add ON or OFF at the end. For example: 

Instead of this: Enabled encryption of installed disks.
Write this: Encrypt installed disks. 

The second message makes sense when the toggle is on or off, whereas the first message only makes sense with the toggle is on. 

We can go through more examples when we meet :)
