### ISSUE TITLE
Find dropdown is not opening in Toolbar component

### ISSUE THREAD

**Issue by cardosogabriel** [patternfly/patternfly-org#293]
In toolbar page, when clicking on the search icon, the dropdown does not open.
http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#_code

**Comment by dlabrecq** [comment]
I see the drop down open on Firefox and Chrome. However, there is no JavaScript added to make this functional. That is, selecting an option won't change the drop down state.

**Comment by cardosogabriel** [comment]
@dlabrecq I found the issue. Somehow this javascript is not working inside patternfly-org: https://github.com/patternfly/patternfly/blob/master/tests/pages/_includes/widgets/layouts/toolbar.html#L104
When you click on the .btn-find button, instead of adding display:block in .find-pf-dropdown-container, it adds display:none. In patternfly it works properly.
Any clue? @jeff-phillips-18 @bleathem @andresgalante

**Comment by dlabrecq** [comment]
Looking at the JavaScript below.

$(".btn-find").click(function () {
  $(".find-pf-dropdown-container").toggle();
});

The code intended to find an element with a find-pf-dropdown-container class is returning undefined. It may work in the Patternfly test page because there is only one element with this class. In pf.org, there are multiple elements with this class. My guess is that the code needs to be written differently (e.g., use a unique ID instead of a style class).

**Comment by cardosogabriel** [comment]
Yes, I was suspecting it was this also. I tried this code:

$(".btn-find").click(function () {
  $(this).parent().find(".find-pf-dropdown-container").toggle();
});

It worked on the patternfly page, but not on patternfly-org. What would be a code that would work?

**Comment by dlabrecq** [comment]
If you obtain the parent div tag, then this code should work.

$(".btn-find").click(function () {
$(this).parent('div').find(".find-pf-dropdown-container").toggle();
});

**Comment by cardosogabriel** [comment]
Thanks Dan.
The code I wrote works. Just sent a PR fixing the issue. Actually there were two problems: the code itself, and the fact that the javascript was being loaded 2 times.

**Comment by LHinson** [comment]
I just check this and it is working. Looks like PR #301 did the trick so I'm closing.
