### ISSUE TITLE
Bug - yarn install fails if running node v16

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#2938]
**Describe the problem**
Followup to #2936 to address the underlying issues causing the errors when trying to install dependencies with Node 16.

**Expected behavior**
Ideally we would be able to run org with a Node version that's still active. Node 14 LTS is set to exit maintenance in roughly one year. https://nodejs.org/en/about/releases/

**Screenshots**
![image](https://user-images.githubusercontent.com/7115053/164788683-0d61bf75-bc39-40ed-802d-6cc38b19ef56.png)

**Any other information?**

**Comment by evwilkin** [comment]
[Related issue](https://github.com/sass/node-sass/pull/3090) and related [fix in patternfly-react](https://github.com/patternfly/patternfly-react/pull/6398)

**Comment by evwilkin** [comment]
Fixed by https://github.com/patternfly/patternfly-org/pull/3047 which removes an outdated dependency which was incompatible with Node >14

<img width="264" alt="Screen Shot 2022-08-01 at 11 28 01 AM" src="https://user-images.githubusercontent.com/8651509/182185191-e2297a0f-1310-48dd-a957-ab7000505d07.png">
