### ISSUE TITLE
Bug - Update all "View source on Github" links at bottom of design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3121]
**Describe the problem**
The "View source on Github" link at the bottom of all design guideline pages is giving a 404 due to the new file structure. Need to update those links to reflect the new structure!

**Expected behavior**
Should link to the github source file.

**Screenshots**
<img width="885" alt="image" src="https://user-images.githubusercontent.com/51165119/183737368-dc5748a2-82fa-4e5a-b957-82d67b48fe60.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/51165119/183737418-70bd926d-1c3d-47a6-97dc-ee4df09caaa5.png">

cc" @evwilkin

**Comment by evwilkin** [comment]
@mmenestr after looking into this, the URL for this actually is dynamic and this bug should be fixed as soon as our release goes out & the website gets updated to reflect it.  This can be [seen on the staging site](https://staging.patternfly.org/v4/components/badge/design-guidelines), which will be promoted to the live site with our release.

More context: we switched from the `/src` directory to the `/patternfly-docs` directory, which is reflected in where these files are hosted on Github, but have not had a release since this change was made to reflect these changes on the website.
