### ISSUE TITLE
Update Banner design guidelines to remove the bottom banners

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3208]
In cases where a banner is put INSIDE of a page body, there should only be a top banner used, and not a bottom banner. Top AND bottom should only be used when the banners show up completely outside of the page.

Need to update the images in our banner design guidelines to match this. Also wouldn't hurt to add a sentence alluding to this in the guidelines.

**Comment by tiyiprh** [comment]
@mmenestr let me know what you think of these changes!

USAGE:

![banner-types](https://user-images.githubusercontent.com/98424339/192596249-7c142111-3301-49b1-ab94-fe674a2f966b.png)

Since the image describes the first banner as default, I think the next sentence explaining when to use it should also say "Default" versus "Basic."

Current:
_A basic banner should only be used when the banner color does not represent status or severity._

WHEN TO USE:

Removing "and bottom" per the issue.

Current:
To indicate that an application/site is offline. In this example, a banner is used to indicate to the user that the site is undergoing maintenance and that they will have limited functionality as a result. The banner is shown at the top _and bottom_ to ensure that the user does not miss this disclaimer. Since this is a general, non-severe message, a default banner was used.

![example-1](https://user-images.githubusercontent.com/98424339/192597208-a4365026-2c22-4864-9cc7-af2a326c0304.png)

VARIATIONS:
Placement:

Current:
_All banners should be a solid bar that spans the top and/or bottom of either:_

Updated sentence:
All banners should be a solid bar spanning the width of either the full page or the main content area of the page.

- The banner should span the top and bottom when it is used for a full page 
![placement-1](https://user-images.githubusercontent.com/98424339/192598251-7d77c630-e61f-4b6f-a3c2-c7dd74f9800d.png)

- The banner should span only the top when it is used for the main content area of the page
![placement-2](https://user-images.githubusercontent.com/98424339/192598345-3e6a8c90-4fc0-42c9-9968-16bf1fd18db8.png)

**Comment by mmenestr** [comment]
@tiyiprh Looks great !! You can go ahead and create a PR with those changes :)
