### ISSUE TITLE
Full page examples in react workspace have extra "Loading..." text at top of page

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3209]
I don't see it in other workspaces (core or org). I'm not sure if it's a docs issue, or something on the react side. It's the same "Loading..." text that you see for a hot second on all workspaces as the example loads, but for some reason there are 2 on the react workspace, and only one goes away when the example shows.

<img width="1169" alt="Screen Shot 2022-09-22 at 7 40 46 PM" src="https://user-images.githubusercontent.com/35148959/191874263-4832f085-5f0a-4493-ac93-71e2873cffa5.png">

cc @nicolethoen @jschuler

**Comment by nicolethoen** [comment]
@jschuler 
It appears that this issue was introduced when [this PR merged into React](https://github.com/patternfly/patternfly-react/pull/7969). I cannot identify any changes that appear that they'd create this issue. There have been a few minor dependency bumps in react/org so maybe it's related to that. Do you have any idea why this is happening? You can see it if  you open any PR's preview surge site and open a full page example/demo. You can also see it on patternfly-react-main.surge.sh's demos like [this one](http://patternfly-react-main.surge.sh/components/alert-group/react-demos/alert-group-toast-with-notification-drawer/).
