### ISSUE TITLE
Bug - Revise quick starts & in-app documentation extension documentation

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#3234]
**Describe the problem**
The pages and tabs under Extensions > Quick starts are affected

**Expected behavior**
Quick starts should be lowercase in the documentation and sentence case in the tabs/menu nav. "in-app documentation" is missing a hyphen in the tabs. There are other areas of the documents that can be tightened up so that they're clear and consistent 👍

**Any other information?**

- Review & edit nav and tab labels for capitalization and hyphen consistency 
- Review & edit each document under the following tabs: About, Basic quick starts, In-app documentation (design guidelines are already in good shape)

**Comment by edonehoo** [comment]
@abigaeljamie I just opened a PR with initial edits. Oddly enough, the content that was on the site didn't match what was in the Github files. There weren't huge differences, but it seems like the website isn't fully up to date with GH. I'm not sure why that would be but I'm just mentioning it since we may need to make sure new edits go live down the line. 

Also, I wasn't sure how to change the tab titles. I tried something, but it may have been the wrong approach. If anyone knows please let me know!
