### ISSUE TITLE
Add guidance on when to use jump links on the left vs on the right of a page

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3285]
Based on this conversation on slack that start around the "jump to section" text, we would like to add guidance on when to use jump links on the left, vs on the right.

![image.png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/259b1dcc-b10b-4f6a-a5e6-2929e37a6d3b)

**Comment by smckinno** [comment]
Documentation Google Doc - https://docs.google.com/document/d/13uUm532aK85PJ4-2GXYJZduvR8eV9QtAln3_YK3EUcM/edit?usp=sharing
Outcome: I believe we should limit the usage of jump links to solely be on the left side of the page simply because the environment for the right jump links (like on Patternfly's site) is very specific in order for it to work/not to break AND because the eye movement across the page isn't nearly as efficient with it being on the right as it is on the left. 
Check out the document for a breakdown of different points/comparisons.

**Comment by smckinno** [comment]
[Google doc summarizing everything 
](https://docs.google.com/document/d/13uUm532aK85PJ4-2GXYJZduvR8eV9QtAln3_YK3EUcM/edit?usp=sharing) 

Rules for the jump links: 
The last thing we want is to have inconsistencies in the UI. We don’t want the user to go from one page (with the jumplinks on the left) to another page (with the jump links on the right). 
However, we realize there can be occasional use cases for both using jump links on the left and right. 
Whatever placement you choose, it is important to be consistent within your site/application

Left side - This is the default option 
If the jump links are being used as a primary navigation element (like complex forms), it should be located on the left side. 
Examples: Wizard steps & vertical table

Right side - case by case situation
If it is more used as a convenience (such as the patternfly site), it should be used on the right side.
Make sure it does not interfere with the consistency of the site/application AND is only used for convenience - not primary navigation 
Can also use it on the right if there is a persistent menu on the left

**Comment by mmenestr** [comment]
@smckinno looks good for the most part! I think to say "used as a convenience" is too vague though - I'm not sure how I would interpret that. I would explicitly state "such as a table of contents", where it is not integral.

**Comment by smckinno** [comment]
updated the doc!

**Comment by smckinno** [comment]
https://docs.google.com/document/d/1fnfnNuAaESZV-hLHveIVKyqSoL4pJNScH5vLmjASDnA/edit?usp=sharing 
Final documentation with final text and visuals that would go into the PF site (and where it would go)
