### ISSUE TITLE
doc-framework: Need to be able to import propComponents from relative path

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3331]
With the introduction of next/deprecated components, some components will need to import `propComponents` (to build API prop tables in the docs) from components living in different component directories. 

i.e. The dropdown-next component in src/next/components/Dropdown needs to import the MenuToggle component props from src/components/MenuToggle

**Comment by evwilkin** [comment]
The issue is coming from [this line in parseMD.js](https://github.com/patternfly/patternfly-org/blob/main/packages/documentation-framework/scripts/md/parseMD.js#L64) which sees that the example file lives in the next directory - specifically that the `source` (tab name) is `react-next` [as defined in patternfly-docs.source.js](https://github.com/patternfly/patternfly-react/blob/v5/packages/react-docs/patternfly-docs/patternfly-docs.source.js#L29).

As a solution, we need to be able to distinguish within a `next` example when the propComponent listed is not a `next` component.  One option would be allowing the user to pass an array or object in place of a propComponent string at the top of an example file which would contain both the propComponent name but also a boolean of whether it is a `next` component (or perhaps a more flexible system which could expand to deprecated or other components as well).

An example is referencing the standard `MenuToggle` component within the `Dropdown-next` example:

<details>
<summary>Example</summary>

**react-core/src/next/components/Dropdown/examples/Dropdown.md**

```
propComponents: ['Dropdown', DropdownGroup, 'DropdownItem', 'DropdownList', ['MenuToggle', false]]
```

**parseMD.js (in documentation-framework package)**

```
const propComponents = [...new Set(frontmatter.propComponents || [])].reduce((acc, componentName) => {
  // const name = getTsDocName(componentName, source === 'react-next');
  const [cName, isNext] = Array.isArray(componentName) ? componentName : [componentName, source === 'react-next'];
  const name = getTsDocName(cName, isNext);

  if (tsDocs[name]) {
    acc.push(tsDocs[name]);
  } else {
    file.message(`Prop component ${name} is missing from tsDocgen`);
  }

  return acc;
}, []);
```

</details>
