### ISSUE TITLE
Data tables footer at https://www.patternfly.org/pattern-library/widgets/#data-tables looks janky

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#342]
<img width="940" alt="screen shot 2017-01-17 at 11 39 35 am" src="https://cloud.githubusercontent.com/assets/895728/22029903/fa3bc50e-dca9-11e6-95f7-9ea3dd6b211a.PNG">

**Comment by bleathem** [comment]
This was caused by the site consuming an updated example template, but CSS from the previous release.  This particular issue is gone now that we have had our release.  We have a separate story for consuming more up-to-date CSS from the git submodule rather than the previous release.  This will prevent such an error from recurring.
