### ISSUE TITLE
Remove Community Extensions page from website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3569]
After discussing with @jessiehuff we decided that the Community Extensions page (https://www.patternfly.org/v4/extensions/community-extensions) is no longer relevant and should be removed as the linked extensions on this page are no longer relevant or have otherwise been exposed as part of our supported extensions library.

cc @evwilkin @edonehoo @andrew-ronaldson

**Comment by mcarrano** [comment]
@edonehoo Yes, that's correct. However we agreed that on the extensions landing page we do want to somehow talk about the process for contributing or requesting a new extension. @jessiehuff any ideas about what to say here? I know this was discussed in the past, but not sure where we landed from a process perspective. If you have a bullet or two, perhaps we can incorporate that into her into text. @edonehoo perhaps you can share your draft text for that page and we'll see where that fits in? Thanks.

**Comment by edonehoo** [comment]
Yep! Here's the landing page PR, including the extensions page: [https://github.com/patternfly/patternfly-org/pull/3535](https://github.com/patternfly/patternfly-org/pull/3535).

**Comment by mcarrano** [comment]
How about this text to get the conversation started:

"Extensions are complete solutions that utilize multiple PatternFly components to address a specific use case. They provide reusable code to span products and platforms to drive consistent experiences across a user’s journey. We welcome ideas and contributions from the community towards growing our extensions library with an eye towards prioritizing those extensions that will be widely used by multiple projects"

@edonehoo @jessiehuff thoughts?

**Comment by edonehoo** [comment]
Sounds good! If I was to tweak that just a bit, maybe:

"Extensions are complex solutions that utilize multiple PatternFly components, typically addressing cross-project use cases. They provide reusable code that can drive consistency throughout a user’s journey across products and platforms. We welcome ideas and contributions for new extensions from the PatternFly community and will prioritize those that can be widely used by multiple projects."

But also where should we direct people to contribute new ideas? The site currently gives instructions for opening a pull request in org, but is that still going to be the proper approach going forward?

**Comment by mcarrano** [comment]
@edonehoo your rewrite is fine, but I specifically changed "complex" to "complete" as I felt like "complex" may have negative connotations, but let me know what you think.

Good question about _how_ to contribute your ideas. I don't think we want people randomly opening PRs. @jessiehuff maybe people would reach out on Slack? We do have an extensions channel. What do you think?

**Comment by edonehoo** [comment]
@mcarrano Ah, yeah I do get what you mean. I guess I was worried that "complete" made it seem like other solutions on the site were "incomplete", but that's a little nitpicky. What do you think about "intricate"? Or we could just drop the adjective maybe. IDK I know this is definitely getting into the weeds hah "complete" also really works fine. 

Sending people to Slack feels a bit more accessible and seems to be where we point people most of the time, so it sounds good to me. But I'll let Jessie chime in as well!

**Comment by jessiehuff** [comment]
I agree with the flow of conversation here where it's tough to decide which adjective to use. I don't mind using "complete" or "hollistic", but I also understand what we mean so it's harder to know what will be clear to others. I always think of extensions like lego kits instead of just using legos, that they're a more opinionated solution. (Whereas components are more composable and can be used for a wide variety of use cases, extensions are often a more specific way of solving a common problem.) So I'm not sure what the word is that would express that haha.

Also, after making sure I'm on the same page with Dana, I think it would make sense to keep the creating an extension section fairly short and allow for flexibility in our process. We're thinking it would make sense to direct them to Github Discussions. That way, they can advocate their solution with other products and see if it makes sense for others as well.
