### ISSUE TITLE
Code example pages for many widgets don't render the widgets

### ISSUE THREAD

**Issue by jamesfalkner** [patternfly/patternfly-org#365]
Several widgets (in fact most of them) don't seem to render correctly:

![screen shot 2017-02-13 at 3 45 19 pm](https://cloud.githubusercontent.com/assets/861894/22934207/21532dc8-f29c-11e6-9b76-b6f299a49c5b.png)

This may be related to #364 but the error message in the dev console is different, so not sure.

**Comment by dabeng** [comment]
Now, the donut charts render well and there are not error on the browser consoles. So I close this issue due to invalid

<img width="1019" alt="screen shot 2018-05-17 at 10 55 07 am" src="https://user-images.githubusercontent.com/5689075/40154577-8fd17a6a-59c1-11e8-98e2-3012c8be9026.png">

<img width="1004" alt="screen shot 2018-05-17 at 10 55 51 am" src="https://user-images.githubusercontent.com/5689075/40154583-9563b394-59c1-11e8-8916-79e30bc8c820.png">

<img width="1017" alt="screen shot 2018-05-17 at 10 56 35 am" src="https://user-images.githubusercontent.com/5689075/40154594-9de025a2-59c1-11e8-8aa0-7456f3fe3769.png">

<img width="1009" alt="screen shot 2018-05-17 at 10 57 46 am" src="https://user-images.githubusercontent.com/5689075/40154598-a2c67120-59c1-11e8-825c-2f2091f75dcc.png">

**Comment by dabeng** [comment]
Now, the donut charts render well and there are not error on the browser consoles. So I close this issue due to invalid.

<img width="1019" alt="screen shot 2018-05-17 at 10 55 07 am" src="https://user-images.githubusercontent.com/5689075/40154577-8fd17a6a-59c1-11e8-98e2-3012c8be9026.png">

<img width="1004" alt="screen shot 2018-05-17 at 10 55 51 am" src="https://user-images.githubusercontent.com/5689075/40154583-9563b394-59c1-11e8-8916-79e30bc8c820.png">

<img width="1017" alt="screen shot 2018-05-17 at 10 56 35 am" src="https://user-images.githubusercontent.com/5689075/40154594-9de025a2-59c1-11e8-8aa0-7456f3fe3769.png">

<img width="1009" alt="screen shot 2018-05-17 at 10 57 46 am" src="https://user-images.githubusercontent.com/5689075/40154598-a2c67120-59c1-11e8-825c-2f2091f75dcc.png">
