### ISSUE TITLE
Update Card View guidelines

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-org#3658]
**Is this a new page or a change to an existing one?**
Existing

**Describe the enhancement**

Per @mmenestr 's feedback on https://github.com/patternfly/patternfly-react/pull/9322 - when a card uses the "clickable and selectable" pattern, the blue border should not appear based on the Card design guidelines: https://staging.patternfly.org/components/card/design-guidelines/#selectable-and-clickable-cards

In order to correctly match the design guidelines for card, the screenshots need to be updated for the following card view design guidelines:

https://staging.patternfly.org/patterns/card-view/design-guidelines#card-views-on-mobile and https://staging.patternfly.org/patterns/card-view/design-guidelines#global-actions

**Comment by mmenestr** [comment]
Thank you for creating this issue @jenny-s51 but the cards in the card view are **only** selectable cards, not clickable AND selectable, so the images linked in staging are actually correct! When cards are ONLY selectable (and _not_ clickable to open a primary detail drawer for example), the cards should have the styling shown in the images.

Those images have actually been updated recently to be different from what you'd currently in the PF website because the styling of everything changed when we introduced "clickable AND selectable" cards. Let me know if this is still confusing, happy to talk through it.
