### ISSUE TITLE
Add link to ConsoleDot module federation article

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#3743]
Martin on ConsoleDot published a [Medium article](https://medium.com/@marvusm.mmi/webpack-module-federation-think-twice-before-sharing-a-dependency-18b3b0e352cb) on using module federation with PatternFly 5, we should look at highlighting it on our website.

**Comment by evwilkin** [comment]
I can imagine 3 options for highlighting an outside post:

1. [Transfer the post](https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publication) to the PatternFly publication and feature it as a normal PF post, with help from the original author.
2. Link to the post where it currently lives, and add "Guest post" or something similar in the title text link.  (This has the downside of not appearing anywhere in the PF Medium even though it's featured on the PF.Org home page).
3. Create a new PatternFly post, which quickly references & links out to the original post.

@edonehoo @hyperkid123 do you have a preference?

**Comment by edonehoo** [comment]
Thanks for sharing! We're always looking feature more stories about experiences using PatternFly on our Medium, so I'd love to add this to our publication if Martin is comforatble with taht . 

It'd also be great **_if_** we could lean even more into the experience using PatternFly, including lessons, observations, what PatternFly particularly helped with, how it worked with other technologies, how it could help others, etc. If it already covers all of the thoughts in these areas, then that's fine too. 

Once we publish it on the PatternFly Medium, we can update the PF.org featured blogs to highlight this one on our homepage 😊

**Comment by Hyperkid123** [comment]
@evwilkin @edonehoo let's just do option 1. AFAIK, nothing much apart from the store URL changes right?

**Comment by evwilkin** [comment]
I believe so, I'll connect with @edonehoo to confirm

**Comment by edonehoo** [comment]
Pretty much! @Hyperkid123 , but we'll make a couple of updates so that it matches the style of our blog (separator images, ending blurb, etc. small things). It also looks like we'll need to update "Patternfly" to "PatternFly", to match our typical capitalization. But these are edits I'm happy to make once you submit your article as a draft! 

I can't link directly to the section of our guide that mentions this, but there are instructions under #8 in the "submission process" section [here](https://medium.com/patternfly/submitting-to-patternflys-medium-publication-d809a75b4ea2). Could you take a swing and let me know if you have any questions?

**Comment by Hyperkid123** [comment]
@edonehoo OK. I'll try to find some time to update the article ASAP. (I am on PTO next week)

**Comment by edonehoo** [comment]
That's okay @Hyperkid123 - we can always fit your into our publishing schedule, so if you can't get to it before your PTO I'll check in with you afterwards 🙂

**Comment by Hyperkid123** [comment]
Well, I did not get to it :slightly_frowning_face: .
