### ISSUE TITLE
Pattern Library Broken

### ISSUE THREAD

**Issue by michael-x** [patternfly/patternfly-org#377]
Looks like http://www.patternfly.org/pattern-library/ is broken due to incompatible components. It is loading jQuery 1.8.3 and bootstrap 3.3.7 which requires at least version 1.9.1 of jQuery.

**Comment by michael-x** [comment]
For a brief moment it did work with a jQuery 2.x version, then reverted back to the incompatible versions.

Is the site load-balanced and not all nodes updated properly?

**Comment by michael-x** [comment]
Most stuff in the patternfly.org/pattern-library (and potentially other areas) requiring JavaScript are still broken. As an example this applies to the navigation on the left (cannot expand/collapse) and to the tabs at the top,

**Comment by bleathem** [comment]
This is caused by the broken bower version string in bootstrap-switch, as described here.  I'll put up a PR downgrading to an earlier bootstrap-switch release until this issue is resolved.
https://github.com/Bttstrp/bootstrap-switch/issues/612

We are also about to merge a PR upgrading to jQuery 3 in our 4.0-dev branch:
https://github.com/patternfly/patternfly/pull/637

**Comment by bleathem** [comment]
The PR with the temporary resolution:
https://github.com/patternfly/patternfly/pull/639
