### ISSUE TITLE
Missing Code examples/links for Filter, Sort, Pagination

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#518]
The Code tab is disabled for the following:

http://www.patternfly.org/pattern-library/forms-and-controls/filter/
http://www.patternfly.org/pattern-library/forms-and-controls/checkbox-filter/
http://www.patternfly.org/pattern-library/forms-and-controls/textbox-filter/
http://www.patternfly.org/pattern-library/forms-and-controls/sort/
http://www.patternfly.org/pattern-library/navigation/pagination/

I know all of these are in angular-patternfly.  I believe most of them are actually in all the js repos.

**Comment by amarie401** [comment]
@mcarrano @LHinson -- I followed the design and added the links for textbox filter and checkbox filter for the repo implementations that fit those designs in my PR to the design repo here: 

[checkbox](https://github.com/patternfly/patternfly-design/pull/537/files#diff-d292bd8d78cfd05ebafcdff80fa0c33dR6) , [textbox](https://github.com/patternfly/patternfly-design/pull/537/files#diff-bea4db7e856707d1d0d26d75e5a1e54a)

I'm not certain of what goes under just regular filter? Do all of those qualify as filter even though they are specific types and have their own pattern? The design tab for filter has links to textbox and checkbox filters, would we want to show those same links in the code tab as well?

**Comment by mcarrano** [comment]
This is a good question @amarie401 . The filter pattern is really composed of multiple parts. As defined in the Filter pattern, the checkbox and textbox filters are specific filter components that plug into a toolbar. But the Filter pattern also defines how filters are reflected within the toolbar by adding "filter chips."

@dtaylor113 in the Angular repos, how do you differentiate between Filter, Textbox Filter, and Checkbox Filter?

**Comment by dtaylor113** [comment]
> @dtaylor113 in the Angular repos, how do you differentiate between Filter, Textbox Filter, and Checkbox Filter?

In angular-patternfly we have pfFilter (Textbox Filter), Checkbox (pfFilterPanel), and "filter chips" (pfFilterResults/pfFilterPanelResults)

**Comment by amarie401** [comment]
I think that since the design tabs has links pointing to textbox filter and checktbox filter should we do the same for mat for the code tab for filter?

**Comment by dtaylor113** [comment]
> I think that since the design tabs has links pointing to textbox filter and checktbox filter should we do the same for mat for the code tab for filter?

Works for me :-)

**Comment by amarie401** [comment]
Textbox filter, Checkbox filter, Sort, and Pagination are now currently available on the code tab for their angular-pf links.  Also as far as adding links to textbox/checkbox filter to the code tab, it seems with the way that it is currently set up, it would require it's own conditional to display it just for the filters code tab (otherwise it will show up on all of the code tabs). Not sure if we should add that to the ``page-pattern`` template for consistency purposes since links are not available on all of the other code tabs (only the links to the framework implementations).

@dtaylor113

**Comment by amarie401** [comment]
Textbox filter, Checkbox filter, Sort, and Pagination are now currently available on the code tab for their angular-pf links.

Also as far as adding links pointing to textbox/checkbox filter to the code tab for filter, it seems with the way that it is currently set up, it would require it's own conditional to display it just for the filter code tab (otherwise it will show up on all of the code tabs).

Not sure if we should add those links to the template for consistency purposes since all of the other code tabs don't link off to different patterns (they only link to the framework implementation showcases).

@dtaylor113

**Comment by dtaylor113** [comment]
> Is the Filter pattern the same as "filter chips"? Should I be adding either pfFilterResults or pfFilterPanelResults to the Filter Pattern code tab as the a-pf implementation? Just want to clarify.

Linking to angular-patternfly's pfFilter and pfFilterPanel will also show the filter chips/result tags, so I don't think we need a specific link for filter results in pf-org. -thanks

**Comment by amarie401** [comment]
Since the missing code example links have already been added I will go ahead and close this issue then.

Thanks!
