### ISSUE TITLE
App launcher examples not showing icons or grid format

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#520]
The examples are meant to show both a grid and list view. The grid is shown by adding a class of `applauncher-pf-block-list` on the `applauncher-pf` list item. The icons are not in the code example at all so they will have to be added. For reference here is the [test page](http://rawgit.com/patternfly/patternfly/master-dist/dist/tests/application-launcher.html) that shows the right examples

**Comment by mcarrano** [comment]
@amarie401 Can you take a look at this? Sounds like there is some gap between the examples shown on the Code page and the PF code implementation. Looks like we're missing some things, It's this page: http://www.patternfly.org/pattern-library/application-framework/launcher/#code

**Comment by amarie401** [comment]
@matthewcarleton @mcarrano  I can take a look at it

**Comment by michpetrov** [comment]
This is caused by patternfly/patternfly#738, I'll send a PR.

**Comment by amarie401** [comment]
So is this caused by hyphenated variables or just missing a class? @michpetrov 

Wasn't it just missing a class and some html includes when we looked over it? @matthewcarleton

**Comment by matthewcarleton** [comment]
@amarie401 we may need to discuss this further. From what I understood that's how it worked but I could be wrong. @mcarrano do you know who we can talk to about how .org structure works?

**Comment by amarie401** [comment]
@matthewcarleton I think the [code.md](https://github.com/patternfly/patternfly-org/blob/master/source/_includes/code/application-framework/launcher/code.md) for the app launcher is what is showing up on org. The design repo uses the ```code.md``` to display the examples which is reflect on org. The md file is also bringing in the includes and I notice there is ```launcher-grid=true/false``` and ```launcher-icons=true/false``` depending on the example. Those must not be working. We would definitely need to investigate this further though.

**Comment by mcarrano** [comment]
Good question about who to ask for more guidance on how these code pages work. @dlabrecq didn't you work on developing the current patternfly.org site at one point? If so, can you shed any light on this?

**Comment by dlabrecq** [comment]
Yes, I worked on the site, but didn't create the overly complex implementation created to support the code.md files from the design repo. Unfortunately, the person who built that has since left the company.

I can say, after looking at the code.md file, that the 'launcher-grid' and 'launcher-icons' attributes are specific to the test page example in Patternfly core.

{% include widgets/layouts/navbar-vertical.html launcher-grid=false launcher-icons=false navindex=8 %}

FYI, pf.org creates a clone the design repo, then uses the above reference from code.md to include that example from another clone of Patternfly core. Although, pf.org still has to build the include correctly with Jekyll -- that's likely the problem. 

Note that pf.org uses Jekyll to build the site, while Patternfly uses different, custom code to generate the same test pages. Jekyll was removed from Patternfly simply so we had one less dev dependency; however, if Jekyll remained in place, we may have picked up the issue much earlier with the Patternfly build.

That said, if the 'launcher-grid' and 'launcher-icons' attributes are not working, take a closer look at the example in Patternfly core. Perhaps you can provide the attributes differently? For example, all the test page examples I created for Patternfly used camel case attribute names (not dashes), so you might consider using launcherIcons and launcherGrid instead?

**Comment by michpetrov** [comment]
@amarie401 @dlabrecq sorry for the delay. The reason this isn't working is because we got rid of the hyphenated variables in patternfly but the example on patternfly.org is using its own code page which has the old variables, they just need to be renamed.
