### ISSUE TITLE
Pattern names on Pattern Overview page should link

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#543]
The Pattern names in the first column of the table on this screen should link to the corresponding pattern page in the library.

**Comment by amarie401** [comment]
After doing some investigation with the way that I'm currently pulling in the design status data: http://www.patternfly.org/patternfly-design/status/pattern-status.json

It would seem that in order to do this, there will need to be some sort of variable in the pf-design repo that links every pattern to it's corresponding overview page on the pf-org site that I can then pull that information from for the table. For example we have links for `impl_jquery`, `impl_angular`, etc. We need something like `impl_org` in each pattern`site.md` file in the design repo and this will need to also be added to each new pattern introduced in the design repo going forward.

@mcarrano @LHinson thoughts? The process will take a bit of time but it is doable if linking the names to their overview page is something we definitely want to include in the table..

**Comment by mcarrano** [comment]
Hmmmm.... This is unfortunate. I thought Brian's old design status page had these links, but now that I look at it again, I see that he linked to the content in GitHub, not on the website. I hate the idea of going through every pattern and updating the site.md for this. Could you build a link if you know the category name and the pattern name @amarie401 ? So you can concatenate "patternfly.org/patternlibrary/+<category-name>/+<pattern-name>" to get the URL for each pattern page. Any reason that wouldn't work?

**Comment by amarie401** [comment]
Great idea @mcarrano I should be able to concatenate a link instead. Will try that route, will be much simpler than going through every pattern and updating the site.md. Thanks!
