### ISSUE TITLE
Max-width Columns

### ISSUE THREAD

**Issue by dash-RH** [patternfly/patternfly-org#68]
I recommend having max-width columns based on legibility standards. See: http://webtypography.net/2.1.2

**Comment by dlabrecq** [comment]
For both the new and old sites, elements expand 100% of the page. For example, the widgets page has a lot of this. I hesitate to make broad changes, but will defer to @LHinson here.

**Comment by LHinson** [comment]
@dash-RH is not the only one to say this and I agree that we should look at it. Curious, what's the level of effort to  adjust this @dlabrecq? We will definitely have to watch out for how this affects our examples.

**Comment by dlabrecq** [comment]
I don't believe the effort would be all that bad. For patterns, the only examples with columns are:

- date picker
- field level help
- forms
- time picker
- forms

Other than "forms", I don't see an issue with the width. (The others are only about 35-40 chars wide.) The forms example would need to be fixed in the patternfly test pages.

Note that inline notifications also expand the width of the page, but this does not use columns.

In the widgets section, the examples with columns are:

- combobox
- date picker
- touch spin
- search

These examples expand the width of the page and can be easily fixed.

The "Count Remaining Characters" example, at the bottom of the widgets page, expands the width of the page, but that intentionally accepts 100 characters -- we don't want to limit that example to 40 characters. Therefore, I would leave this example alone.

**Comment by dlabrecq** [comment]
@LHinson I misspoke above. When I first read the suggested doc, it mentioned limiting the size of columns. I was thinking of textarea elements in our pages, which have a columns attribute (cols). This specifies the visible width of a text area. Typically, input elements are no longer than 40-45 characters, which is about the limit suggested in the doc.

That said, I now realize that the doc is speaking about limiting the number of characters that appear in any single line in the page to 45-75 characters. To put this in perspective, the attached screen shot is about 75 characters wide or 650px. 

I'm thinking a designer should take a good look at this? This seems very limiting and doesn't leave much room for images, examples, etc. Like I said, most input elements are already 40 characters in length.

![screen shot 2016-06-02 at 7 25 51 pm](https://cloud.githubusercontent.com/assets/17481322/15764391/96cec60c-28f8-11e6-96bc-74fd28c0b1f7.png)

**Comment by andresgalante** [comment]
@dlabrecq @LHinson @dash-RH I see no way out this one at the moment 😞 
The change would be too large in the structure of the website and will affect the design. Not something we can do in a week.
@LHinson Can we open a jira issue to keep this in mind for website improvements?

**Comment by LHinson** [comment]
Yes @andresgalante There is now a story created. See: https://patternfly.atlassian.net/browse/PTNFLY-1536

**Comment by LHinson** [comment]
Closing as this has been addressed. Thanks!
