### ISSUE TITLE
Mapping Search Terms - Searching by related keywords

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#756]
During this sprint we will add the functionality to search by related "search terms".

**Comment by rachael-phillips** [comment]
@jschuler created a pull request. A limitation is that they support only 20 synonyms. Single word synonyms can only be supported.

**Comment by rachael-phillips** [comment]
Here's the document that @gdoyle1 created: https://docs.google.com/spreadsheets/d/1G5oPR7mhm4V5SRdxNB6JVCsuU3RI2MmHGktWVfGEeLE/edit?usp=drive_web&ouid=108667088289925826391

**Comment by gdoyle1** [comment]
@rachael-phillips @jschuler 

I've updated the sheet so that it follows the guidelines we spoke about during the meeting. There are now only 20 buckets of synonyms that map to components. Many of the buckets include synonyms that relate only to certain components. There is a key explaining how that works on the sheet. Please let me know if you have any questions as I'm sure it'll be confusing! https://docs.google.com/spreadsheets/d/1G5oPR7mhm4V5SRdxNB6JVCsuU3RI2MmHGktWVfGEeLE/edit?usp=sharing
