### ISSUE TITLE
Slightly fuzzy image on home page (resolution)

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#864]
Using: Firefox on Mac, Retina Screen

The image is a little low res looking on a Retina screen
![Xnip2019-04-26_14-10-58](https://user-images.githubusercontent.com/23172038/56827569-3267ef00-682d-11e9-8710-d1fe419b5b5f.jpg)

**Comment by gdoyle1** [comment]
What do think of this solution? @mcarrano @rachael-phillips 
https://marvelapp.com/5hed282

**Comment by rachael-phillips** [comment]
Hi @gdoyle1 the reason I like this is that it is scalable for the long-term, we won't have to update the image as it becomes outdated. is it possible to send over a png or jpeg, any image file works of what this will look like in the context of the full homepage. When we put it all together, you may see things that before weren't as apparent.

**Comment by gdoyle1** [comment]
I added an example to the marvel project! I just changed the margin width a bit where the text starts. @rachael-phillips

**Comment by rachael-phillips** [comment]
Awesome - thanks. It's hard for me to tell from the mockup, but are all of the font sizes consistent and the same as the middle section "About PatternFly"?

**Comment by gdoyle1** [comment]
They are the same but look a little different since I screenshotted the page - I used inspect and based the sizes off that! So they're definitely accurate. @rachael-phillips

**Comment by rachael-phillips** [comment]
Nice! I think it's looking great @gdoyle1  - my only question is do we want to use icons in this way when we have sophisticated graphics in the middle "About" section. What do you think @mcarrano ? And @mceledonia would you mind giving this a review, as well?

**Comment by mcarrano** [comment]
I like it!

**Comment by gdoyle1** [comment]
Let me know if there are any changes I need to make here!

**Comment by mceledonia** [comment]
Nice work @gdoyle1! I'd recommend using SVGs for the icons and background as we would completely avoid the resolution/quality issue of using a raster format.

I think the icons are fine here but they might need some cleanup, for example this one isn't aligned in a couple places:
<img width="180" alt="image" src="https://user-images.githubusercontent.com/30935938/74549032-e94c6d00-4f1c-11ea-93fc-c8ce3becf01b.png">

As for the text size, maybe try using the same header/body sizes as the section above? 

Since this is the bottom of the page I feel like we should maybe repeat the call to action button styling at the bottom, basically using the same button styling as "Why PatternFly" at the top but around the "Get started" buttons at the bottom. Here's a super quick mock up of what I mean: 

![image](https://user-images.githubusercontent.com/30935938/74549496-bce52080-4f1d-11ea-9cce-4d2c6c90e283.png)

**Comment by gdoyle1** [comment]
I made changes based on your feedback @mceledonia ! https://marvelapp.com/5hed282

**Comment by gdoyle1** [comment]
Spec is here: https://marvelapp.com/5hed282. Attached are the three SVGs for the icons 
[HomepageSVGs.zip](https://github.com/patternfly/patternfly-org/files/4232500/HomepageSVGs.zip)
