### ISSUE TITLE
[UI]The home page not a full screen size design (PatternFly beta)

### ISSUE THREAD

**Issue by zhutaoredhat** [patternfly/patternfly-org#87]
![beta](https://cloud.githubusercontent.com/assets/13375283/15662470/a12b5dbc-2723-11e6-8e23-8cfe10c81c35.png)
![online](https://cloud.githubusercontent.com/assets/13375283/15662471/a1a3185c-2723-11e6-9b0c-46abb5c2ba05.png)

When I  review the PatternFly home page on a 23 inch screen of PC,  found it is not a full screen size design which looks not very well.

**Comment by dlabrecq** [comment]
@LHinson Is this layout intentional?

**Comment by LHinson** [comment]
looping in @sjcox-rh @rox Let me know if I need to create a story for this.

**Comment by dlabrecq** [comment]
@sjcox-rh @rox It looks to me that this new layout was by design. Can you please confirm?

**Comment by dlabrecq** [comment]
It turns out that this was a change introduced by #32 to allow for sticky footers. It took a while to trace down, but the underlying problem is that the html selector was changed from "height:100%;" to "min-height:100%". 

html {
  min-height: 100%; << Doesn't work on home page
  position: relative;
}

My solution is to override the html selector for the home page, only.
