### ISSUE TITLE
Tables in Style Guide need padding

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-org#935]
Columns are too close together at https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology

<img width="1015" alt="Screen Shot 2019-04-26 at 2 38 52 PM" src="https://user-images.githubusercontent.com/7014965/56829215-254cff00-6831-11e9-9b8d-80395aee149b.png">

<img width="1018" alt="Screen Shot 2019-04-26 at 2 40 24 PM" src="https://user-images.githubusercontent.com/7014965/56829271-4d3c6280-6831-11e9-8675-bd382c376c08.png">

Seen on Desktop (Chrome).

**Comment by ajacobs21e** [comment]
Also this table is very hard to read with each row being middle aligned. It would be much easier to read if all text on a row was top aligned.

**Comment by ajacobs21e** [comment]
Also the vertical spacing is inconsistent for this page. A little more space between rows in this table, abbreviation, and timeframe ones would help readability. There's much more space between rows when there are bulleted lists.

The bulleted list for month abbreviations takes up a lot of room. I think this would be fine to put into a multi-column table instead of bullets with one per line.

**Comment by rachael-phillips** [comment]
What browser are you in here? I'm not seeing the issue in Chrome from my side

**Comment by ajacobs21e** [comment]
I'm also using Chrome
