### ISSUE TITLE
Remove dark theme button until more progress has been made on dark theme

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-org#960]
For all of the React components, the dark mode toggle is present in the documentation but does not actually do anything.  Suggest removing or disabling the toggle if no dark mode is supported.

![image](https://user-images.githubusercontent.com/3739227/56830143-8f66a380-6833-11e9-888c-fb72ec25df5a.png)

**Comment by mturley** [comment]
This seemed similar enough not to open a different issue: while on the React side the dark theme button doesn't do anything at all, on the HTML side it always sets a dark background color, however some components do not change in dark mode (e.g. Accordion is still white) and some do (e.g. Card turns dark).

So it appears that some of the HTML components do not support dark mode at all, and the button should probably be removed/disabled for those. And since some components' CSS actually does support a dark mode (e.g. Card) that dark mode button on the React side should be fixed, not removed/disabled. I.e. the dark mode button should be consistently enabled or disabled on HTML/React pages for the same component.

**Comment by rachael-phillips** [comment]
Thanks so much for filing! Yes, this is a known issue that we should remove this until we have made more progress on our dark theme strategy. For now we should remove the theming icon from both the HTML/CSS and React views. Michael Celedonia and I will go through and identify which ones should appear on the site soon.
