### ISSUE TITLE
Dark theme & full page

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#961]
After toggling dark theme, that setting does not stay when I open in full page and there is no way to toggle dark theme when in full page.

![image](https://user-images.githubusercontent.com/23172038/56830158-9beafc00-6833-11e9-80e9-7dadbdcba069.png)

**Comment by rachael-phillips** [comment]
Thanks for filing and good find!

**Comment by rachael-phillips** [comment]
Update here: We are going to remove the dark theme icon for now because we are still crafting our strategy around dark theme components. So next steps on this is that Michael Celedonia and I will go through and identify which components will be dark theme. I'm going to close this issue because we have an issue open for that work.
